import {
  CHARACTER_ARMOR_LIMITS,
  CHARACTER_ARMOR_VALUE_IDS,
  CHARACTER_ATTACK_TYPE_IDS,
  CHARACTER_CLASS_IDS,
  CHARACTER_DIFFICULTY_IDS,
  CHARACTER_GAME_MODE_IDS,
  CHARACTER_LEVEL_LIMITS,
  CHARACTER_MATERIAL_LIMITS,
  CHARACTER_MAG_LIMITS,
  CHARACTER_SPECIAL_IDS,
  CHARACTER_SHIFTA_LEVELS,
  CHARACTER_ZALURE_LEVELS,
  CHARACTER_SHIELD_VALUE_IDS,
  CHARACTER_SHIELD_LIMITS,
  CHARACTER_UNIT_VALUE_IDS,
  CHARACTER_WEAPON_VALUE_IDS,
  DEFAULT_CHARACTER_CONFIG,
} from '@pso/shared'
import { Schema, model } from 'mongoose'

const characterConfigSchema = new Schema(
  {
    classId: {
      type: String,
      enum: CHARACTER_CLASS_IDS,
      required: true,
    },
    level: {
      type: Number,
      min: CHARACTER_LEVEL_LIMITS.min,
      max: CHARACTER_LEVEL_LIMITS.max,
      required: true,
    },
    difficulty: {
      type: String,
      enum: CHARACTER_DIFFICULTY_IDS,
      default: DEFAULT_CHARACTER_CONFIG.difficulty,
      required: true,
    },
    gameMode: {
      type: String,
      enum: CHARACTER_GAME_MODE_IDS,
      default: 'normal',
      required: true,
    },
    attackType: {
      type: String,
      enum: CHARACTER_ATTACK_TYPE_IDS,
      default: 'normal',
      required: true,
    },
    shiftaLevel: {
      type: Number,
      enum: CHARACTER_SHIFTA_LEVELS,
      default: 0,
      required: true,
    },
    zalureLevel: {
      type: Number,
      enum: CHARACTER_ZALURE_LEVELS,
      default: 0,
      required: true,
    },
    weaponId: {
      type: String,
      enum: CHARACTER_WEAPON_VALUE_IDS,
      default: 'none',
      required: true,
    },
    specialId: {
      type: String,
      enum: CHARACTER_SPECIAL_IDS,
      default: 'none',
      required: true,
    },
    grind: {
      type: Number,
      min: 0,
      max: 35,
      default: 0,
      required: true,
    },
    armorId: {
      type: String,
      enum: CHARACTER_ARMOR_VALUE_IDS,
      default: 'frame',
      required: true,
    },
    armorDfp: {
      type: Number,
      min: CHARACTER_ARMOR_LIMITS.dfpMin,
      max: CHARACTER_ARMOR_LIMITS.dfpMax,
      default: 7,
      required: true,
    },
    armorEvp: {
      type: Number,
      min: CHARACTER_ARMOR_LIMITS.evpMin,
      max: CHARACTER_ARMOR_LIMITS.evpMax,
      default: 7,
      required: true,
    },
    shieldId: {
      type: String,
      enum: CHARACTER_SHIELD_VALUE_IDS,
      default: 'barrier',
      required: true,
    },
    shieldDfp: {
      type: Number,
      min: CHARACTER_SHIELD_LIMITS.dfpMin,
      max: CHARACTER_SHIELD_LIMITS.dfpMax,
      default: 7,
      required: true,
    },
    shieldEvp: {
      type: Number,
      min: CHARACTER_SHIELD_LIMITS.evpMin,
      max: CHARACTER_SHIELD_LIMITS.evpMax,
      default: 30,
      required: true,
    },
    magDef: {
      type: Number,
      min: CHARACTER_MAG_LIMITS.defMin,
      max: CHARACTER_MAG_LIMITS.defMax,
      default: CHARACTER_MAG_LIMITS.defMin,
      required: true,
    },
    magPow: {
      type: Number,
      min: CHARACTER_MAG_LIMITS.powMin,
      max: CHARACTER_MAG_LIMITS.powMax,
      default: 0,
      required: true,
    },
    magDex: {
      type: Number,
      min: CHARACTER_MAG_LIMITS.dexMin,
      max: CHARACTER_MAG_LIMITS.dexMax,
      default: 0,
      required: true,
    },
    magMind: {
      type: Number,
      min: CHARACTER_MAG_LIMITS.mindMin,
      max: CHARACTER_MAG_LIMITS.mindMax,
      default: 0,
      required: true,
    },
    materials: {
      hp: {
        type: Number,
        min: 0,
        max: CHARACTER_MATERIAL_LIMITS.hpMax,
        default: CHARACTER_MATERIAL_LIMITS.hpMax,
        required: true,
      },
      tp: {
        type: Number,
        min: 0,
        max: CHARACTER_MATERIAL_LIMITS.tpMax,
        default: CHARACTER_MATERIAL_LIMITS.tpMax,
        required: true,
      },
      power: {
        type: Number,
        min: 0,
        max: CHARACTER_MATERIAL_LIMITS.regularTotalExtended,
        default: 0,
        required: true,
      },
      def: {
        type: Number,
        min: 0,
        max: CHARACTER_MATERIAL_LIMITS.regularTotalExtended,
        default: 0,
        required: true,
      },
      mind: {
        type: Number,
        min: 0,
        max: CHARACTER_MATERIAL_LIMITS.regularTotalExtended,
        default: 0,
        required: true,
      },
      evade: {
        type: Number,
        min: 0,
        max: CHARACTER_MATERIAL_LIMITS.regularTotalExtended,
        default: 0,
        required: true,
      },
      luck: {
        type: Number,
        min: 0,
        max: CHARACTER_MATERIAL_LIMITS.regularTotalExtended,
        default: 0,
        required: true,
      },
    },
    unitSlot1Id: {
      type: String,
      enum: CHARACTER_UNIT_VALUE_IDS,
      default: 'none',
      required: true,
    },
    unitSlot2Id: {
      type: String,
      enum: CHARACTER_UNIT_VALUE_IDS,
      default: 'none',
      required: true,
    },
    unitSlot3Id: {
      type: String,
      enum: CHARACTER_UNIT_VALUE_IDS,
      default: 'none',
      required: true,
    },
    unitSlot4Id: {
      type: String,
      enum: CHARACTER_UNIT_VALUE_IDS,
      default: 'none',
      required: true,
    },
    weaponAttributes: {
      enemy: {
        type: Number,
        min: -5,
        max: 100,
        default: 100,
        required: true,
      },
      hit: {
        type: Number,
        min: -5,
        max: 100,
        default: 100,
        required: true,
      },
    },
  },
  {
    timestamps: true,
  },
)

export const CharacterConfigModel = model('CharacterConfig', characterConfigSchema)
