import type { CharacterArmorOption } from './index.js'

const ZERO_CHARACTER_STAT_BONUSES = {
  hp: 0,
  tp: 0,
  atp: 0,
  dfp: 0,
  mst: 0,
  ata: 0,
  evp: 0,
  lck: 0,
  efr: 0,
  eic: 0,
  eth: 0,
  edk: 0,
  elt: 0,
}

export const ADDITIONAL_CHARACTER_ARMOR_OPTIONS: CharacterArmorOption[] = [
  {
    id: 'frame',
    label: "Frame",
    type: 'Armor',
    rarity: 0,
    requiredLevel: 0,
    requirement: "Aucun",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 5,
    dfpMax: 7,
    mst: 0,
    ata: 0,
    evpMin: 5,
    evpMax: 7,
    lck: 0,
    efr: 5,
    eic: 0,
    eth: 0,
    edk: 5,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 5, edk: 5 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010100',
  },
  {
    id: 'armor',
    label: "Armor",
    type: 'Armor',
    rarity: 0,
    requiredLevel: 4,
    requirement: "Level 4",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 7,
    dfpMax: 9,
    mst: 0,
    ata: 0,
    evpMin: 7,
    evpMax: 9,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 5,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, eth: 5 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010100',
  },
  {
    id: 'psy_armor',
    label: "Psy Armor",
    type: 'Armor',
    rarity: 1,
    requiredLevel: 7,
    requirement: "Level 7",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 10,
    dfpMax: 13,
    mst: 0,
    ata: 0,
    evpMin: 10,
    evpMax: 12,
    lck: 0,
    efr: 0,
    eic: 5,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, eic: 5 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010100',
  },
  {
    id: 'giga_frame',
    label: "Giga Frame",
    type: 'Armor',
    rarity: 1,
    requiredLevel: 10,
    requirement: "Level 10",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 15,
    dfpMax: 19,
    mst: 0,
    ata: 0,
    evpMin: 12,
    evpMax: 14,
    lck: 0,
    efr: 0,
    eic: 4,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, eic: 4 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010100',
  },
  {
    id: 'soul_frame',
    label: "Soul Frame",
    type: 'Armor',
    rarity: 2,
    requiredLevel: 13,
    requirement: "Level 13",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 20,
    dfpMax: 24,
    mst: 0,
    ata: 0,
    evpMin: 15,
    evpMax: 17,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 3,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, eth: 3 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010100',
  },
  {
    id: 'cross_armor',
    label: "Cross Armor",
    type: 'Armor',
    rarity: 2,
    requiredLevel: 16,
    requirement: "Level 16",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 25,
    dfpMax: 29,
    mst: 0,
    ata: 0,
    evpMin: 17,
    evpMax: 19,
    lck: 0,
    efr: 3,
    eic: 0,
    eth: 0,
    edk: 5,
    elt: 10,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 3, edk: 5, elt: 10 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010100',
  },
  {
    id: 'solid_frame',
    label: "Solid Frame",
    type: 'Armor',
    rarity: 3,
    requiredLevel: 19,
    requirement: "Level 19",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 30,
    dfpMax: 34,
    mst: 0,
    ata: 0,
    evpMin: 20,
    evpMax: 22,
    lck: 0,
    efr: 0,
    eic: 3,
    eth: 0,
    edk: 0,
    elt: 10,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, eic: 3, elt: 10 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010100',
  },
  {
    id: 'brave_armor',
    label: "Brave Armor",
    type: 'Armor',
    rarity: 3,
    requiredLevel: 23,
    requirement: "Level 23",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 35,
    dfpMax: 39,
    mst: 0,
    ata: 0,
    evpMin: 22,
    evpMax: 24,
    lck: 0,
    efr: 4,
    eic: 0,
    eth: 3,
    edk: 10,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 4, eth: 3, edk: 10 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010100',
  },
  {
    id: 'hyper_frame',
    label: "Hyper Frame",
    type: 'Armor',
    rarity: 4,
    requiredLevel: 27,
    requirement: "Level 27",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 40,
    dfpMax: 44,
    mst: 0,
    ata: 0,
    evpMin: 25,
    evpMax: 27,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 5,
    edk: 12,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, eth: 5, edk: 12 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010100',
  },
  {
    id: 'grand_armor',
    label: "Grand Armor",
    type: 'Armor',
    rarity: 4,
    requiredLevel: 31,
    requirement: "Level 31",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 45,
    dfpMax: 49,
    mst: 0,
    ata: 0,
    evpMin: 27,
    evpMax: 29,
    lck: 0,
    efr: 0,
    eic: 4,
    eth: 0,
    edk: 0,
    elt: 10,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, eic: 4, elt: 10 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010100',
  },
  {
    id: 'shock_frame',
    label: "Shock Frame",
    type: 'Armor',
    rarity: 5,
    requiredLevel: 35,
    requirement: "Level 35",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 50,
    dfpMax: 54,
    mst: 0,
    ata: 0,
    evpMin: 30,
    evpMax: 32,
    lck: 0,
    efr: 3,
    eic: 0,
    eth: 0,
    edk: 6,
    elt: 6,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 3, edk: 6, elt: 6 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010100',
  },
  {
    id: 'kings_frame',
    label: "King's Frame",
    type: 'Armor',
    rarity: 5,
    requiredLevel: 39,
    requirement: "Level 39",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 55,
    dfpMax: 59,
    mst: 0,
    ata: 0,
    evpMin: 32,
    evpMax: 34,
    lck: 0,
    efr: 0,
    eic: 3,
    eth: 0,
    edk: 10,
    elt: 14,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, eic: 3, edk: 10, elt: 14 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010100',
  },
  {
    id: 'dragon_frame',
    label: "Dragon Frame",
    type: 'Armor',
    rarity: 6,
    requiredLevel: 43,
    requirement: "Level 43",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 60,
    dfpMax: 64,
    mst: 0,
    ata: 0,
    evpMin: 35,
    evpMax: 37,
    lck: 0,
    efr: 8,
    eic: 0,
    eth: 0,
    edk: 5,
    elt: 20,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 8, edk: 5, elt: 20 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010100',
  },
  {
    id: 'absorb_armor',
    label: "Absorb Armor",
    type: 'Armor',
    rarity: 6,
    requiredLevel: 47,
    requirement: "Level 47",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 65,
    dfpMax: 69,
    mst: 0,
    ata: 0,
    evpMin: 37,
    evpMax: 39,
    lck: 0,
    efr: 3,
    eic: 0,
    eth: 3,
    edk: 13,
    elt: 13,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 3, eth: 3, edk: 13, elt: 13 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010100',
  },
  {
    id: 'protect_frame',
    label: "Protect Frame",
    type: 'Armor',
    rarity: 7,
    requiredLevel: 51,
    requirement: "Level 51",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 70,
    dfpMax: 74,
    mst: 0,
    ata: 0,
    evpMin: 40,
    evpMax: 42,
    lck: 0,
    efr: 3,
    eic: 5,
    eth: 0,
    edk: 12,
    elt: 15,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 3, eic: 5, edk: 12, elt: 15 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010100',
  },
  {
    id: 'general_armor',
    label: "General Armor",
    type: 'Armor',
    rarity: 7,
    requiredLevel: 55,
    requirement: "Level 55",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 75,
    dfpMax: 79,
    mst: 0,
    ata: 0,
    evpMin: 42,
    evpMax: 44,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 5,
    edk: 20,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, eth: 5, edk: 20 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010100',
  },
  {
    id: 'perfect_frame',
    label: "Perfect Frame",
    type: 'Armor',
    rarity: 7,
    requiredLevel: 59,
    requirement: "Level 59",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 80,
    dfpMax: 84,
    mst: 0,
    ata: 0,
    evpMin: 45,
    evpMax: 47,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 15,
    elt: 15,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 15, elt: 15 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010100',
  },
  {
    id: 'valiant_frame',
    label: "Valiant Frame",
    type: 'Armor',
    rarity: 7,
    requiredLevel: 63,
    requirement: "Level 63",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 85,
    dfpMax: 89,
    mst: 0,
    ata: 0,
    evpMin: 47,
    evpMax: 49,
    lck: 0,
    efr: 0,
    eic: 5,
    eth: 0,
    edk: 18,
    elt: 15,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, eic: 5, edk: 18, elt: 15 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010100',
  },
  {
    id: 'imperial_armor',
    label: "Imperial Armor",
    type: 'Armor',
    rarity: 8,
    requiredLevel: 67,
    requirement: "Level 67",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 90,
    dfpMax: 94,
    mst: 0,
    ata: 0,
    evpMin: 50,
    evpMax: 52,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 13,
    elt: 16,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 13, elt: 16 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010100',
  },
  {
    id: 'holiness_armor',
    label: "Holiness Armor",
    type: 'Armor',
    rarity: 8,
    requiredLevel: 71,
    requirement: "Level 71",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 95,
    dfpMax: 99,
    mst: 0,
    ata: 0,
    evpMin: 52,
    evpMax: 54,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 25,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, elt: 25 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010100',
  },
  {
    id: 'guardian_armor',
    label: "Guardian Armor",
    type: 'Armor',
    rarity: 8,
    requiredLevel: 75,
    requirement: "Level 75",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 100,
    dfpMax: 104,
    mst: 0,
    ata: 0,
    evpMin: 55,
    evpMax: 57,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 18,
    elt: 16,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 18, elt: 16 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010100',
  },
  {
    id: 'divinity_armor',
    label: "Divinity Armor",
    type: 'Armor',
    rarity: 8,
    requiredLevel: 78,
    requirement: "Level 78",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 105,
    dfpMax: 109,
    mst: 0,
    ata: 0,
    evpMin: 57,
    evpMax: 59,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 18,
    elt: 17,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 18, elt: 17 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010100',
  },
  {
    id: 'ultimate_frame',
    label: "Ultimate Frame",
    type: 'Armor',
    rarity: 8,
    requiredLevel: 80,
    requirement: "Level 80",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 110,
    dfpMax: 114,
    mst: 0,
    ata: 0,
    evpMin: 60,
    evpMax: 62,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 18,
    elt: 18,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 18, elt: 18 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010100',
  },
  {
    id: 'celestial_armor',
    label: "Celestial Armor",
    type: 'Armor',
    rarity: 8,
    requiredLevel: 85,
    requirement: "Level 85",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 120,
    dfpMax: 130,
    mst: 0,
    ata: 0,
    evpMin: 72,
    evpMax: 82,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 20,
    elt: 20,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 20, elt: 20 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010100',
  },
  {
    id: 'dress_plate',
    label: "Dress Plate",
    type: 'Armor',
    rarity: 9,
    requiredLevel: 0,
    requirement: "Aucun",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 30,
    dfpMax: 30,
    mst: 0,
    ata: 0,
    evpMin: 30,
    evpMax: 30,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 70,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 70 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hucast', 'ramar', 'racast', 'fomar', 'fonewm'],
    hex: '010180',
  },
  {
    id: 'kroes_sweater',
    label: "Kroe's Sweater",
    type: 'Armor',
    rarity: 9,
    requiredLevel: 0,
    requirement: "Aucun",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 1,
    dfpMax: 1,
    mst: 0,
    ata: 0,
    evpMin: 1,
    evpMax: 1,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: ['hunewearl'],
    hex: '010180',
  },
  {
    id: 'wedding_dress',
    label: "Wedding Dress",
    type: 'Armor',
    rarity: 9,
    requiredLevel: 0,
    requirement: "Aucun",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 30,
    dfpMax: 30,
    mst: 0,
    ata: 0,
    evpMin: 30,
    evpMax: 30,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 70,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, elt: 70 },
    conditionalEffects: [],
    compatibleClasses: ['hunewearl', 'hucaseal', 'ramarl', 'racaseal', 'fomarl', 'fonewearl'],
    hex: '010180',
  },
  {
    id: 'force_field',
    label: "Force Field",
    type: 'Armor',
    rarity: 9,
    requiredLevel: 28,
    requirement: "Level 28",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 40,
    dfpMax: 48,
    mst: 0,
    ata: 0,
    evpMin: 80,
    evpMax: 88,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 18,
    elt: 25,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 18, elt: 25 },
    conditionalEffects: [],
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '010180',
  },
  {
    id: 'hunter_field',
    label: "Hunter Field",
    type: 'Armor',
    rarity: 9,
    requiredLevel: 28,
    requirement: "Level 28",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 60,
    dfpMax: 68,
    mst: 0,
    ata: 0,
    evpMin: 80,
    evpMax: 88,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 20,
    elt: 15,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 20, elt: 15 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal'],
    hex: '010180',
  },
  {
    id: 'ranger_field',
    label: "Ranger Field",
    type: 'Armor',
    rarity: 9,
    requiredLevel: 28,
    requirement: "Level 28",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 50,
    dfpMax: 58,
    mst: 0,
    ata: 0,
    evpMin: 80,
    evpMax: 88,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 18,
    elt: 20,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 18, elt: 20 },
    conditionalEffects: [],
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010180',
  },
  {
    id: 'dirty_lifejacket',
    label: "Dirty Lifejacket",
    type: 'Armor',
    rarity: 9,
    requiredLevel: 100,
    requirement: "Level 100",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 5,
    dfpMax: 5,
    mst: 0,
    ata: 0,
    evpMin: 5,
    evpMax: 5,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 20,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 20 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010180',
  },
  {
    id: 'union_field',
    label: "Union Field",
    type: 'Armor',
    rarity: 10,
    requiredLevel: 50,
    requirement: "Level 50",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 0,
    dfpMax: 200,
    mst: 0,
    ata: 0,
    evpMin: 50,
    evpMax: 50,
    lck: 0,
    efr: 5,
    eic: 5,
    eth: 5,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 5, eic: 5, eth: 5 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010180',
  },
  {
    id: 'd_parts_ver1_01',
    label: "D-Parts ver1.01",
    type: 'Armor',
    rarity: 10,
    requiredLevel: 51,
    requirement: "Level 51",
    hp: 0,
    tp: 0,
    atp: 35,
    dfpMin: 115,
    dfpMax: 125,
    mst: 0,
    ata: 0,
    evpMin: 85,
    evpMax: 92,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 15,
    elt: 25,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, atp: 35, edk: 15, elt: 25 },
    conditionalEffects: [],
    compatibleClasses: ['hucast', 'hucaseal', 'racast', 'racaseal'],
    hex: '010180',
  },
  {
    id: 'attribute_plate',
    label: "Attribute Plate",
    type: 'Armor',
    rarity: 10,
    requiredLevel: 54,
    requirement: "Level 54",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 105,
    dfpMax: 113,
    mst: 0,
    ata: 0,
    evpMin: 85,
    evpMax: 93,
    lck: 0,
    efr: 5,
    eic: 5,
    eth: 5,
    edk: 20,
    elt: 25,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 5, eic: 5, eth: 5, edk: 20, elt: 25 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010180',
  },
  {
    id: 'graviton_plate',
    label: "Graviton Plate",
    type: 'Armor',
    rarity: 10,
    requiredLevel: 54,
    requirement: "Level 54",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 125,
    dfpMax: 133,
    mst: 0,
    ata: -10,
    evpMin: 0,
    evpMax: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 18,
    elt: 15,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, ata: -10, edk: 18, elt: 15 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010180',
  },
  {
    id: 'parasite_wear_de_rol',
    label: "Parasite Wear: De Rol",
    type: 'Armor',
    rarity: 10,
    requiredLevel: 54,
    requirement: "Level 54",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 120,
    dfpMax: 170,
    mst: 0,
    ata: 0,
    evpMin: 100,
    evpMax: 120,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 20,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 20 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'ramar', 'ramarl', 'fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '010180',
  },
  {
    id: 'stink_frame',
    label: "Stink Frame",
    type: 'Armor',
    rarity: 10,
    requiredLevel: 54,
    requirement: "Level 54",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 40,
    dfpMax: 125,
    mst: 0,
    ata: 0,
    evpMin: 15,
    evpMax: 100,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 22,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 22 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010180',
  },
  {
    id: 'revival_garment',
    label: "Revival Garment",
    type: 'Armor',
    rarity: 10,
    requiredLevel: 58,
    requirement: "Level 58",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 85,
    dfpMax: 90,
    mst: 0,
    ata: 0,
    evpMin: 60,
    evpMax: 70,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 18,
    elt: 20,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 18, elt: 20 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010180',
  },
  {
    id: 'spirit_garment',
    label: "Spirit Garment",
    type: 'Armor',
    rarity: 10,
    requiredLevel: 71,
    requirement: "Level 71",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 100,
    dfpMax: 107,
    mst: 0,
    ata: 0,
    evpMin: 92,
    evpMax: 97,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 20,
    elt: 25,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 20, elt: 25 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010180',
  },
  {
    id: 'alliance_uniform',
    label: "Alliance Uniform",
    type: 'Armor',
    rarity: 10,
    requiredLevel: 76,
    requirement: "Level 76",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 88,
    dfpMax: 100,
    mst: 0,
    ata: 0,
    evpMin: 0,
    evpMax: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 5,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 5 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010180',
  },
  {
    id: 'custom_frame_ver_oo',
    label: "Custom Frame ver.OO",
    type: 'Armor',
    rarity: 10,
    requiredLevel: 76,
    requirement: "Level 76",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 80,
    dfpMax: 90,
    mst: 0,
    ata: 0,
    evpMin: 85,
    evpMax: 95,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 13,
    elt: 18,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 13, elt: 18 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010180',
  },
  {
    id: 'dbs_armor',
    label: "DB's Armor",
    type: 'Armor',
    rarity: 10,
    requiredLevel: 76,
    requirement: "Level 76",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 85,
    dfpMax: 95,
    mst: 0,
    ata: 0,
    evpMin: 80,
    evpMax: 90,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 13,
    elt: 20,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 13, elt: 20 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010180',
  },
  {
    id: 'flowens_frame',
    label: "Flowen's Frame",
    type: 'Armor',
    rarity: 10,
    requiredLevel: 76,
    requirement: "Level 76",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 82,
    dfpMax: 92,
    mst: 0,
    ata: 0,
    evpMin: 72,
    evpMax: 82,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 15,
    elt: 18,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 15, elt: 18 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010180',
  },
  {
    id: 'infantry_mantle',
    label: "Infantry Mantle",
    type: 'Armor',
    rarity: 10,
    requiredLevel: 76,
    requirement: "Level 76",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 92,
    dfpMax: 102,
    mst: 0,
    ata: 0,
    evpMin: 96,
    evpMax: 106,
    lck: 0,
    efr: 2,
    eic: 2,
    eth: 2,
    edk: 6,
    elt: 6,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 2, eic: 2, eth: 2, edk: 6, elt: 6 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010180',
  },
  {
    id: 'samurai_armor',
    label: "Samurai Armor",
    type: 'Armor',
    rarity: 10,
    requiredLevel: 80,
    requirement: "Level 80",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 121,
    dfpMax: 121,
    mst: 0,
    ata: 0,
    evpMin: 102,
    evpMax: 102,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010180',
  },
  {
    id: 'd_parts_ver2_10',
    label: "D-Parts ver2.10",
    type: 'Armor',
    rarity: 10,
    requiredLevel: 81,
    requirement: "Level 81",
    hp: 0,
    tp: 0,
    atp: 10,
    dfpMin: 125,
    dfpMax: 135,
    mst: 0,
    ata: 0,
    evpMin: 90,
    evpMax: 98,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 20,
    elt: 25,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, atp: 10, edk: 20, elt: 25 },
    conditionalEffects: [],
    compatibleClasses: ['hucast', 'hucaseal', 'racast', 'racaseal'],
    hex: '010180',
  },
  {
    id: 'officer_uniform',
    label: "Officer Uniform",
    type: 'Armor',
    rarity: 10,
    requiredLevel: 89,
    requirement: "Level 89",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 114,
    dfpMax: 128,
    mst: 0,
    ata: 0,
    evpMin: 0,
    evpMax: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 20,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 20 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'ramar', 'ramarl', 'fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '010180',
  },
  {
    id: 'infantry_gear',
    label: "Infantry Gear",
    type: 'Armor',
    rarity: 10,
    requiredLevel: 91,
    requirement: "Level 91",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 118,
    dfpMax: 130,
    mst: 0,
    ata: 0,
    evpMin: 45,
    evpMax: 53,
    lck: 0,
    efr: 1,
    eic: 1,
    eth: 1,
    edk: 8,
    elt: 6,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 1, eic: 1, eth: 1, edk: 8, elt: 6 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010180',
  },
  {
    id: 'spirit_cuirass',
    label: "Spirit Cuirass",
    type: 'Armor',
    rarity: 10,
    requiredLevel: 98,
    requirement: "Level 98",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 122,
    dfpMax: 129,
    mst: 0,
    ata: 0,
    evpMin: 116,
    evpMax: 121,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010180',
  },
  {
    id: 'congeal_cloak',
    label: "Congeal Cloak",
    type: 'Armor',
    rarity: 10,
    requiredLevel: 99,
    requirement: "Level 99",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 168,
    dfpMax: 176,
    mst: 0,
    ata: 0,
    evpMin: 143,
    evpMax: 151,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 18,
    edk: 3,
    elt: 3,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, eth: 18, edk: 3, elt: 3 },
    conditionalEffects: [],
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '010180',
  },
  {
    id: 'cursed_cloak',
    label: "Cursed Cloak",
    type: 'Armor',
    rarity: 10,
    requiredLevel: 99,
    requirement: "Level 99",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 172,
    dfpMax: 180,
    mst: 0,
    ata: 0,
    evpMin: 146,
    evpMax: 154,
    lck: 0,
    efr: 3,
    eic: 3,
    eth: 3,
    edk: 18,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 3, eic: 3, eth: 3, edk: 18 },
    conditionalEffects: [],
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '010180',
  },
  {
    id: 'ignition_cloak',
    label: "Ignition Cloak",
    type: 'Armor',
    rarity: 10,
    requiredLevel: 99,
    requirement: "Level 99",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 168,
    dfpMax: 176,
    mst: 0,
    ata: 0,
    evpMin: 143,
    evpMax: 151,
    lck: 0,
    efr: 18,
    eic: 0,
    eth: 0,
    edk: 3,
    elt: 3,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 18, edk: 3, elt: 3 },
    conditionalEffects: [],
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '010180',
  },
  {
    id: 'select_cloak',
    label: "Select Cloak",
    type: 'Armor',
    rarity: 10,
    requiredLevel: 99,
    requirement: "Level 99",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 172,
    dfpMax: 180,
    mst: 0,
    ata: 0,
    evpMin: 146,
    evpMax: 154,
    lck: 0,
    efr: 3,
    eic: 3,
    eth: 3,
    edk: 0,
    elt: 18,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 3, eic: 3, eth: 3, elt: 18 },
    conditionalEffects: [],
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '010180',
  },
  {
    id: 'tempest_cloak',
    label: "Tempest Cloak",
    type: 'Armor',
    rarity: 10,
    requiredLevel: 99,
    requirement: "Level 99",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 168,
    dfpMax: 176,
    mst: 0,
    ata: 0,
    evpMin: 143,
    evpMax: 151,
    lck: 0,
    efr: 0,
    eic: 18,
    eth: 0,
    edk: 3,
    elt: 3,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, eic: 18, edk: 3, elt: 3 },
    conditionalEffects: [],
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '010180',
  },
  {
    id: 'black_odoshi_domaru',
    label: "Black Odoshi Domaru",
    type: 'Armor',
    rarity: 10,
    requiredLevel: 101,
    requirement: "Level 101",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 124,
    dfpMax: 134,
    mst: 0,
    ata: 0,
    evpMin: 82,
    evpMax: 92,
    lck: 0,
    efr: 1,
    eic: 1,
    eth: 1,
    edk: 1,
    elt: 1,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 1, eic: 1, eth: 1, edk: 1, elt: 1 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal'],
    hex: '010180',
  },
  {
    id: 'chu_chu_fever',
    label: "Chu Chu Fever",
    type: 'Armor',
    rarity: 10,
    requiredLevel: 101,
    requirement: "Level 101",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 5,
    dfpMax: 5,
    mst: 0,
    ata: 0,
    evpMin: 5,
    evpMax: 5,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010180',
  },
  {
    id: 'commander_uniform',
    label: "Commander Uniform",
    type: 'Armor',
    rarity: 10,
    requiredLevel: 101,
    requirement: "Level 101",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 180,
    dfpMax: 196,
    mst: 0,
    ata: 0,
    evpMin: 85,
    evpMax: 85,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 25,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 25 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'ramar', 'ramarl', 'fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '010180',
  },
  {
    id: 'lieutenant_gear',
    label: "Lieutenant Gear",
    type: 'Armor',
    rarity: 10,
    requiredLevel: 101,
    requirement: "Level 101",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 168,
    dfpMax: 186,
    mst: 0,
    ata: 0,
    evpMin: 112,
    evpMax: 128,
    lck: 0,
    efr: 3,
    eic: 3,
    eth: 3,
    edk: 12,
    elt: 8,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 3, eic: 3, eth: 3, edk: 12, elt: 8 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'ramar', 'ramarl', 'fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '010180',
  },
  {
    id: 'lieutenant_mantle',
    label: "Lieutenant Mantle",
    type: 'Armor',
    rarity: 10,
    requiredLevel: 101,
    requirement: "Level 101",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 195,
    dfpMax: 216,
    mst: 0,
    ata: 0,
    evpMin: 126,
    evpMax: 144,
    lck: 0,
    efr: 6,
    eic: 6,
    eth: 6,
    edk: 16,
    elt: 12,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 6, eic: 6, eth: 6, edk: 16, elt: 12 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'ramar', 'ramarl', 'fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '010180',
  },
  {
    id: 'morning_prayer',
    label: "Morning Prayer",
    type: 'Armor',
    rarity: 10,
    requiredLevel: 101,
    requirement: "Level 101",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 120,
    dfpMax: 130,
    mst: 0,
    ata: 0,
    evpMin: 140,
    evpMax: 160,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 20,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, elt: 20 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010180',
  },
  {
    id: 'red_coat',
    label: "Red Coat",
    type: 'Armor',
    rarity: 10,
    requiredLevel: 101,
    requirement: "Level 101",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 152,
    dfpMax: 162,
    mst: 0,
    ata: 0,
    evpMin: 131,
    evpMax: 141,
    lck: 0,
    efr: 8,
    eic: 8,
    eth: 8,
    edk: 12,
    elt: 12,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 8, eic: 8, eth: 8, edk: 12, elt: 12 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010180',
  },
  {
    id: 'red_odoshi_domaru',
    label: "Red Odoshi Domaru",
    type: 'Armor',
    rarity: 10,
    requiredLevel: 101,
    requirement: "Level 101",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 112,
    dfpMax: 122,
    mst: 0,
    ata: 0,
    evpMin: 108,
    evpMax: 118,
    lck: 0,
    efr: 2,
    eic: 2,
    eth: 2,
    edk: 2,
    elt: 2,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 2, eic: 2, eth: 2, edk: 2, elt: 2 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal'],
    hex: '010180',
  },
  {
    id: 'revival_cuirass',
    label: "Revival Cuirass",
    type: 'Armor',
    rarity: 10,
    requiredLevel: 101,
    requirement: "Level 101",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 134,
    dfpMax: 139,
    mst: 0,
    ata: 0,
    evpMin: 94,
    evpMax: 104,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010180',
  },
  {
    id: 'thirteen',
    label: "Thirteen",
    type: 'Armor',
    rarity: 10,
    requiredLevel: 101,
    requirement: "Level 101",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 113,
    dfpMax: 121,
    mst: 0,
    ata: 0,
    evpMin: 136,
    evpMax: 144,
    lck: 0,
    efr: 2,
    eic: 2,
    eth: 2,
    edk: 16,
    elt: 8,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 2, eic: 2, eth: 2, edk: 16, elt: 8 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010180',
  },
  {
    id: 'star_cuirass',
    label: "Star Cuirass",
    type: 'Armor',
    rarity: 10,
    requiredLevel: 111,
    requirement: "Level 111",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 250,
    dfpMax: 270,
    mst: 0,
    ata: 0,
    evpMin: 0,
    evpMax: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: ['hucast', 'hucaseal', 'racast', 'racaseal'],
    hex: '010180',
  },
  {
    id: 'stealth_suit',
    label: "Stealth Suit",
    type: 'Armor',
    rarity: 10,
    requiredLevel: 120,
    requirement: "Level 120",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 1,
    dfpMax: 1,
    mst: 0,
    ata: 0,
    evpMin: 300,
    evpMax: 325,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010180',
  },
  {
    id: 'black_hound_cuirass',
    label: "Black Hound Cuirass",
    type: 'Armor',
    rarity: 10,
    requiredLevel: 121,
    requirement: "Level 121",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 300,
    dfpMax: 330,
    mst: 0,
    ata: 0,
    evpMin: -200,
    evpMax: -200,
    lck: 0,
    efr: 2,
    eic: 2,
    eth: 2,
    edk: 2,
    elt: 2,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 2, eic: 2, eth: 2, edk: 2, elt: 2 },
    conditionalEffects: [],
    compatibleClasses: ['hucast', 'hucaseal', 'racast', 'racaseal'],
    hex: '010180',
  },
  {
    id: 'black_odoshi_red_nimaidou',
    label: "Black Odoshi Red Nimaidou",
    type: 'Armor',
    rarity: 10,
    requiredLevel: 135,
    requirement: "Level 135",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 128,
    dfpMax: 138,
    mst: 0,
    ata: 0,
    evpMin: 143,
    evpMax: 153,
    lck: 0,
    efr: 5,
    eic: 5,
    eth: 5,
    edk: 5,
    elt: 5,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 5, eic: 5, eth: 5, edk: 5, elt: 5 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal'],
    hex: '010180',
  },
  {
    id: 'sense_plate',
    label: "Sense Plate",
    type: 'Armor',
    rarity: 10,
    requiredLevel: 141,
    requirement: "Level 141",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 25,
    dfpMax: 32,
    mst: 0,
    ata: 0,
    evpMin: 30,
    evpMax: 38,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 20,
    elt: 25,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 20, elt: 25 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010180',
  },
  {
    id: 'parasite_wear_nelgal',
    label: "Parasite Wear: Nelgal",
    type: 'Armor',
    rarity: 11,
    requiredLevel: 66,
    requirement: "Level 66",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 145,
    dfpMax: 195,
    mst: 0,
    ata: 0,
    evpMin: 85,
    evpMax: 105,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 20,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 20 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'ramar', 'ramarl', 'fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '010180',
  },
  {
    id: 'crimson_coat',
    label: "Crimson Coat",
    type: 'Armor',
    rarity: 11,
    requiredLevel: 101,
    requirement: "Level 101",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 158,
    dfpMax: 170,
    mst: 0,
    ata: 0,
    evpMin: 136,
    evpMax: 148,
    lck: 0,
    efr: 10,
    eic: 10,
    eth: 10,
    edk: 14,
    elt: 14,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 10, eic: 10, eth: 10, edk: 14, elt: 14 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010180',
  },
  {
    id: 'flame_garment',
    label: "Flame Garment",
    type: 'Armor',
    rarity: 11,
    requiredLevel: 101,
    requirement: "Level 101",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 180,
    dfpMax: 230,
    mst: 0,
    ata: 0,
    evpMin: 114,
    evpMax: 134,
    lck: 0,
    efr: 5,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 5 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010180',
  },
  {
    id: 'guard_wave',
    label: "Guard Wave",
    type: 'Armor',
    rarity: 11,
    requiredLevel: 101,
    requirement: "Level 101",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 173,
    dfpMax: 223,
    mst: 0,
    ata: 0,
    evpMin: 110,
    evpMax: 130,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 18,
    elt: 20,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 18, elt: 20 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010180',
  },
  {
    id: 'luminous_field',
    label: "Luminous Field",
    type: 'Armor',
    rarity: 11,
    requiredLevel: 101,
    requirement: "Level 101",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 206,
    dfpMax: 256,
    mst: 0,
    ata: 0,
    evpMin: 124,
    evpMax: 144,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 15,
    elt: 15,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 15, elt: 15 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010180',
  },
  {
    id: 'mother_garb',
    label: "Mother Garb",
    type: 'Armor',
    rarity: 11,
    requiredLevel: 101,
    requirement: "Level 101",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 165,
    dfpMax: 180,
    mst: 0,
    ata: 0,
    evpMin: 85,
    evpMax: 90,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 18,
    elt: 18,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 18, elt: 18 },
    conditionalEffects: [],
    compatibleClasses: ['fonewm'],
    hex: '010180',
  },
  {
    id: 'brightness_circle',
    label: "Brightness Circle",
    type: 'Armor',
    rarity: 11,
    requiredLevel: 111,
    requirement: "Level 111",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 190,
    dfpMax: 240,
    mst: 0,
    ata: 0,
    evpMin: 116,
    evpMax: 136,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 25,
    elt: 20,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 25, elt: 20 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010180',
  },
  {
    id: 'df_field',
    label: "DF Field",
    type: 'Armor',
    rarity: 11,
    requiredLevel: 121,
    requirement: "Level 121",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 203,
    dfpMax: 253,
    mst: 0,
    ata: 0,
    evpMin: 116,
    evpMax: 136,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 17,
    elt: 22,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 17, elt: 22 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010180',
  },
  {
    id: 'electro_frame',
    label: "Electro Frame",
    type: 'Armor',
    rarity: 11,
    requiredLevel: 122,
    requirement: "Level 122",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 196,
    dfpMax: 246,
    mst: 0,
    ata: 0,
    evpMin: 120,
    evpMax: 140,
    lck: 0,
    efr: 5,
    eic: 0,
    eth: 5,
    edk: 5,
    elt: 5,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 5, eth: 5, edk: 5, elt: 5 },
    conditionalEffects: [],
    compatibleClasses: ['hucast', 'hucaseal', 'racast', 'racaseal'],
    hex: '010180',
  },
  {
    id: 'love_heart',
    label: "Love Heart",
    type: 'Armor',
    rarity: 11,
    requiredLevel: 131,
    requirement: "Level 131",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 196,
    dfpMax: 246,
    mst: 0,
    ata: 0,
    evpMin: 140,
    evpMax: 160,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 17,
    elt: 20,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 17, elt: 20 },
    conditionalEffects: [],
    compatibleClasses: ['hunewearl', 'hucaseal', 'ramarl', 'racaseal', 'fomarl', 'fonewearl'],
    hex: '010180',
  },
  {
    id: 'smoking_plate',
    label: "Smoking Plate",
    type: 'Armor',
    rarity: 11,
    requiredLevel: 131,
    requirement: "Level 131",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 223,
    dfpMax: 273,
    mst: 0,
    ata: 0,
    evpMin: 122,
    evpMax: 142,
    lck: 0,
    efr: 5,
    eic: 0,
    eth: 0,
    edk: 20,
    elt: 25,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 5, edk: 20, elt: 25 },
    conditionalEffects: [],
    compatibleClasses: ['fonewm'],
    hex: '010180',
  },
  {
    id: 'sweetheart',
    label: "Sweetheart",
    type: 'Armor',
    rarity: 11,
    requiredLevel: 131,
    requirement: "Level 131",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 176,
    dfpMax: 226,
    mst: 0,
    ata: 0,
    evpMin: 164,
    evpMax: 184,
    lck: 0,
    efr: 2,
    eic: 2,
    eth: 2,
    edk: 10,
    elt: 10,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 2, eic: 2, eth: 2, edk: 10, elt: 10 },
    conditionalEffects: [],
    compatibleClasses: ['hunewearl', 'hucaseal', 'ramarl', 'racaseal', 'fomarl', 'fonewearl'],
    hex: '010180',
  },
  {
    id: 'sacred_cloth',
    label: "Sacred Cloth",
    type: 'Armor',
    rarity: 11,
    requiredLevel: 144,
    requirement: "Level 144",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 100,
    dfpMax: 150,
    mst: 0,
    ata: 0,
    evpMin: 50,
    evpMax: 70,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 15,
    elt: 20,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 15, elt: 20 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010180',
  },
  {
    id: 'aura_field',
    label: "Aura Field",
    type: 'Armor',
    rarity: 11,
    requiredLevel: 152,
    requirement: "Level 152",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 235,
    dfpMax: 285,
    mst: 0,
    ata: 0,
    evpMin: 134,
    evpMax: 154,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 20,
    elt: 20,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 20, elt: 20 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'ramar', 'ramarl', 'fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '010180',
  },
  {
    id: 'parasite_wear_vajulla',
    label: "Parasite Wear: Vajulla",
    type: 'Armor',
    rarity: 12,
    requiredLevel: 89,
    requirement: "Level 89",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 155,
    dfpMax: 205,
    mst: 0,
    ata: 0,
    evpMin: 100,
    evpMax: 120,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 20,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 20 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'ramar', 'ramarl', 'fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '010180',
  },
  {
    id: 'mother_garb_plus',
    label: "Mother Garb+",
    type: 'Armor',
    rarity: 12,
    requiredLevel: 101,
    requirement: "Level 101",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 175,
    dfpMax: 190,
    mst: 0,
    ata: 0,
    evpMin: 95,
    evpMax: 100,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 21,
    elt: 21,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 21, elt: 21 },
    conditionalEffects: [],
    compatibleClasses: ['fonewm'],
    hex: '010180',
  },
  {
    id: 'blue_odoshi_violet_nimaidou',
    label: "Blue Odoshi Violet Nimaidou",
    type: 'Armor',
    rarity: 12,
    requiredLevel: 150,
    requirement: "Level 150",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 156,
    dfpMax: 166,
    mst: 0,
    ata: 0,
    evpMin: 181,
    evpMax: 191,
    lck: 0,
    efr: 8,
    eic: 8,
    eth: 8,
    edk: 8,
    elt: 8,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 8, eic: 8, eth: 8, edk: 8, elt: 8 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal'],
    hex: '010180',
  },
  {
    id: 'virus_armor_lafuteria',
    label: "Virus Armor: Lafuteria",
    type: 'Armor',
    rarity: 12,
    requiredLevel: 156,
    requirement: "Level 156",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 240,
    dfpMax: 290,
    mst: 0,
    ata: 0,
    evpMin: 90,
    evpMax: 110,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 15,
    elt: 15,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 15, elt: 15 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'ramar', 'ramarl', 'fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '010180',
  },
]
