import type { CharacterShieldOption } from './index.js'

const ZERO_CHARACTER_STAT_BONUSES = {
  hp: 0,
  tp: 0,
  atp: 0,
  dfp: 0,
  mst: 0,
  ata: 0,
  evp: 0,
  lck: 0,
  efr: 0,
  eic: 0,
  eth: 0,
  edk: 0,
  elt: 0,
}

export const ADDITIONAL_CHARACTER_SHIELD_OPTIONS: CharacterShieldOption[] = [
  {
    id: 'barrier',
    label: "Barrier",
    type: 'Shield',
    rarity: 0,
    requiredLevel: 0,
    requirement: "Aucun",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 2,
    dfpMax: 7,
    mst: 0,
    ata: 0,
    evpMin: 25,
    evpMax: 30,
    lck: 0,
    efr: 20,
    eic: 15,
    eth: 20,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 20, eic: 15, eth: 20 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010200',
  },
  {
    id: 'shield',
    label: "Shield",
    type: 'Shield',
    rarity: 0,
    requiredLevel: 4,
    requirement: "Level 4",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 4,
    dfpMax: 9,
    mst: 0,
    ata: 0,
    evpMin: 32,
    evpMax: 37,
    lck: 0,
    efr: 20,
    eic: 15,
    eth: 20,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 20, eic: 15, eth: 20 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010200',
  },
  {
    id: 'core_shield',
    label: "Core Shield",
    type: 'Shield',
    rarity: 1,
    requiredLevel: 7,
    requirement: "Level 7",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 6,
    dfpMax: 11,
    mst: 0,
    ata: 0,
    evpMin: 40,
    evpMax: 45,
    lck: 0,
    efr: 18,
    eic: 15,
    eth: 18,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 18, eic: 15, eth: 18 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010200',
  },
  {
    id: 'giga_shield',
    label: "Giga Shield",
    type: 'Shield',
    rarity: 2,
    requiredLevel: 10,
    requirement: "Level 10",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 8,
    dfpMax: 13,
    mst: 0,
    ata: 0,
    evpMin: 47,
    evpMax: 52,
    lck: 0,
    efr: 20,
    eic: 18,
    eth: 20,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 20, eic: 18, eth: 20 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010200',
  },
  {
    id: 'soul_barrier',
    label: "Soul Barrier",
    type: 'Shield',
    rarity: 3,
    requiredLevel: 13,
    requirement: "Level 13",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 10,
    dfpMax: 15,
    mst: 0,
    ata: 0,
    evpMin: 55,
    evpMax: 60,
    lck: 0,
    efr: 19,
    eic: 19,
    eth: 19,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 19, eic: 19, eth: 19 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010200',
  },
  {
    id: 'hard_shield',
    label: "Hard Shield",
    type: 'Shield',
    rarity: 3,
    requiredLevel: 16,
    requirement: "Level 16",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 12,
    dfpMax: 17,
    mst: 0,
    ata: 0,
    evpMin: 57,
    evpMax: 62,
    lck: 0,
    efr: 20,
    eic: 20,
    eth: 20,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 20, eic: 20, eth: 20 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010200',
  },
  {
    id: 'brave_barrier',
    label: "Brave Barrier",
    type: 'Shield',
    rarity: 4,
    requiredLevel: 19,
    requirement: "Level 19",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 14,
    dfpMax: 19,
    mst: 0,
    ata: 0,
    evpMin: 65,
    evpMax: 70,
    lck: 0,
    efr: 20,
    eic: 18,
    eth: 20,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 20, eic: 18, eth: 20 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010200',
  },
  {
    id: 'solid_shield',
    label: "Solid Shield",
    type: 'Shield',
    rarity: 4,
    requiredLevel: 23,
    requirement: "Level 23",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 16,
    dfpMax: 21,
    mst: 0,
    ata: 0,
    evpMin: 72,
    evpMax: 77,
    lck: 0,
    efr: 20,
    eic: 20,
    eth: 20,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 20, eic: 20, eth: 20 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010200',
  },
  {
    id: 'flame_barrier',
    label: "Flame Barrier",
    type: 'Shield',
    rarity: 5,
    requiredLevel: 27,
    requirement: "Level 27",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 19,
    dfpMax: 24,
    mst: 0,
    ata: 0,
    evpMin: 85,
    evpMax: 90,
    lck: 0,
    efr: 30,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 30 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010200',
  },
  {
    id: 'plasma_barrier',
    label: "Plasma Barrier",
    type: 'Shield',
    rarity: 5,
    requiredLevel: 31,
    requirement: "Level 31",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 21,
    dfpMax: 26,
    mst: 0,
    ata: 0,
    evpMin: 92,
    evpMax: 97,
    lck: 0,
    efr: 0,
    eic: 30,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, eic: 30 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010200',
  },
  {
    id: 'freeze_barrier',
    label: "Freeze Barrier",
    type: 'Shield',
    rarity: 5,
    requiredLevel: 35,
    requirement: "Level 35",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 23,
    dfpMax: 28,
    mst: 0,
    ata: 0,
    evpMin: 100,
    evpMax: 105,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 30,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, eth: 30 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010200',
  },
  {
    id: 'psychic_barrier',
    label: "Psychic Barrier",
    type: 'Shield',
    rarity: 6,
    requiredLevel: 39,
    requirement: "Level 39",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 26,
    dfpMax: 31,
    mst: 0,
    ata: 0,
    evpMin: 110,
    evpMax: 115,
    lck: 0,
    efr: 22,
    eic: 22,
    eth: 21,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 22, eic: 22, eth: 21 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010200',
  },
  {
    id: 'general_shield',
    label: "General Shield",
    type: 'Shield',
    rarity: 6,
    requiredLevel: 43,
    requirement: "Level 43",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 29,
    dfpMax: 34,
    mst: 0,
    ata: 0,
    evpMin: 120,
    evpMax: 125,
    lck: 0,
    efr: 28,
    eic: 19,
    eth: 19,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 28, eic: 19, eth: 19 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010200',
  },
  {
    id: 'protect_barrier',
    label: "Protect Barrier",
    type: 'Shield',
    rarity: 7,
    requiredLevel: 47,
    requirement: "Level 47",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 32,
    dfpMax: 37,
    mst: 0,
    ata: 0,
    evpMin: 130,
    evpMax: 135,
    lck: 0,
    efr: 25,
    eic: 25,
    eth: 15,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 25, eic: 25, eth: 15 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010200',
  },
  {
    id: 'glorious_shield',
    label: "Glorious Shield",
    type: 'Shield',
    rarity: 7,
    requiredLevel: 51,
    requirement: "Level 51",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 35,
    dfpMax: 40,
    mst: 0,
    ata: 0,
    evpMin: 140,
    evpMax: 145,
    lck: 0,
    efr: 25,
    eic: 25,
    eth: 25,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 25, eic: 25, eth: 25 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010200',
  },
  {
    id: 'imperial_barrier',
    label: "Imperial Barrier",
    type: 'Shield',
    rarity: 8,
    requiredLevel: 55,
    requirement: "Level 55",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 38,
    dfpMax: 43,
    mst: 0,
    ata: 0,
    evpMin: 150,
    evpMax: 155,
    lck: 0,
    efr: 28,
    eic: 20,
    eth: 28,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 28, eic: 20, eth: 28 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010200',
  },
  {
    id: 'guardian_shield',
    label: "Guardian Shield",
    type: 'Shield',
    rarity: 8,
    requiredLevel: 59,
    requirement: "Level 59",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 41,
    dfpMax: 46,
    mst: 0,
    ata: 0,
    evpMin: 160,
    evpMax: 165,
    lck: 0,
    efr: 10,
    eic: 10,
    eth: 10,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 10, eic: 10, eth: 10 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010200',
  },
  {
    id: 'divinity_barrier',
    label: "Divinity Barrier",
    type: 'Shield',
    rarity: 8,
    requiredLevel: 63,
    requirement: "Level 63",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 44,
    dfpMax: 49,
    mst: 0,
    ata: 0,
    evpMin: 170,
    evpMax: 175,
    lck: 0,
    efr: 27,
    eic: 27,
    eth: 30,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 27, eic: 27, eth: 30 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010200',
  },
  {
    id: 'ultimate_shield',
    label: "Ultimate Shield",
    type: 'Shield',
    rarity: 8,
    requiredLevel: 67,
    requirement: "Level 67",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 47,
    dfpMax: 52,
    mst: 0,
    ata: 0,
    evpMin: 180,
    evpMax: 185,
    lck: 0,
    efr: 30,
    eic: 28,
    eth: 28,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 30, eic: 28, eth: 28 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010200',
  },
  {
    id: 'spiritual_shield',
    label: "Spiritual Shield",
    type: 'Shield',
    rarity: 8,
    requiredLevel: 71,
    requirement: "Level 71",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 50,
    dfpMax: 55,
    mst: 0,
    ata: 0,
    evpMin: 190,
    evpMax: 195,
    lck: 0,
    efr: 28,
    eic: 28,
    eth: 28,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 28, eic: 28, eth: 28 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010200',
  },
  {
    id: 'celestial_shield',
    label: "Celestial Shield",
    type: 'Shield',
    rarity: 8,
    requiredLevel: 75,
    requirement: "Level 75",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 52,
    dfpMax: 57,
    mst: 0,
    ata: 0,
    evpMin: 200,
    evpMax: 205,
    lck: 0,
    efr: 30,
    eic: 30,
    eth: 30,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 30, eic: 30, eth: 30 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010200',
  },
  {
    id: 'bunny_ears',
    label: "Bunny Ears",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 0,
    requirement: "Aucun",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 2,
    dfpMax: 2,
    mst: 0,
    ata: 0,
    evpMin: 25,
    evpMax: 25,
    lck: 0,
    efr: 1,
    eic: 1,
    eth: 1,
    edk: 1,
    elt: 1,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 1, eic: 1, eth: 1, edk: 1, elt: 1 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'cat_ears',
    label: "Cat Ears",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 0,
    requirement: "Aucun",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 2,
    dfpMax: 2,
    mst: 0,
    ata: 0,
    evpMin: 25,
    evpMax: 25,
    lck: 0,
    efr: 1,
    eic: 1,
    eth: 1,
    edk: 1,
    elt: 1,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 1, eic: 1, eth: 1, edk: 1, elt: 1 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'assist_barrier',
    label: "Assist Barrier",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 6,
    requirement: "Level 6",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 2,
    dfpMax: 7,
    mst: 0,
    ata: 0,
    evpMin: 25,
    evpMax: 30,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'blue_barrier',
    label: "Blue Barrier",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 6,
    requirement: "Level 6",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 2,
    dfpMax: 7,
    mst: 0,
    ata: 0,
    evpMin: 25,
    evpMax: 30,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'foie_merge',
    label: "Foie Merge",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 6,
    requirement: "Level 6",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 2,
    dfpMax: 7,
    mst: 0,
    ata: 0,
    evpMin: 25,
    evpMax: 30,
    lck: 0,
    efr: 5,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 5 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'recovery_barrier',
    label: "Recovery Barrier",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 6,
    requirement: "Level 6",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 2,
    dfpMax: 7,
    mst: 0,
    ata: 0,
    evpMin: 25,
    evpMax: 30,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'red_barrier',
    label: "Red Barrier",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 6,
    requirement: "Level 6",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 2,
    dfpMax: 7,
    mst: 0,
    ata: 0,
    evpMin: 25,
    evpMax: 30,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'yellow_barrier',
    label: "Yellow Barrier",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 6,
    requirement: "Level 6",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 2,
    dfpMax: 7,
    mst: 0,
    ata: 0,
    evpMin: 25,
    evpMax: 30,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'barta_merge',
    label: "Barta Merge",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 7,
    requirement: "Level 7",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 2,
    dfpMax: 7,
    mst: 0,
    ata: 0,
    evpMin: 25,
    evpMax: 30,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 5,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, eth: 5 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'zonde_merge',
    label: "Zonde Merge",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 8,
    requirement: "Level 8",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 2,
    dfpMax: 7,
    mst: 0,
    ata: 0,
    evpMin: 25,
    evpMax: 30,
    lck: 0,
    efr: 0,
    eic: 5,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, eic: 5 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'resta_merge',
    label: "Resta Merge",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 11,
    requirement: "Level 11",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 2,
    dfpMax: 7,
    mst: 0,
    ata: 0,
    evpMin: 25,
    evpMax: 30,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 10,
    elt: 15,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 10, elt: 15 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'gifoie_merge',
    label: "Gifoie Merge",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 12,
    requirement: "Level 12",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 2,
    dfpMax: 7,
    mst: 0,
    ata: 0,
    evpMin: 25,
    evpMax: 30,
    lck: 0,
    efr: 10,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 10 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'anti_merge',
    label: "Anti Merge",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 13,
    requirement: "Level 13",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 2,
    dfpMax: 7,
    mst: 0,
    ata: 0,
    evpMin: 25,
    evpMax: 30,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 15,
    elt: 10,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 15, elt: 10 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'deband_merge',
    label: "Deband Merge",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 14,
    requirement: "Level 14",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 2,
    dfpMax: 7,
    mst: 0,
    ata: 0,
    evpMin: 25,
    evpMax: 30,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 15,
    elt: 10,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 15, elt: 10 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'gibarta_merge',
    label: "Gibarta Merge",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 14,
    requirement: "Level 14",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 2,
    dfpMax: 7,
    mst: 0,
    ata: 0,
    evpMin: 25,
    evpMax: 30,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 10,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, eth: 10 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'works_guard',
    label: "Works Guard",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 14,
    requirement: "Level 14",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 11,
    dfpMax: 16,
    mst: 0,
    ata: 0,
    evpMin: 75,
    evpMax: 80,
    lck: 0,
    efr: 5,
    eic: 5,
    eth: 5,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 5, eic: 5, eth: 5 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'gizonde_merge',
    label: "Gizonde Merge",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 15,
    requirement: "Level 15",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 2,
    dfpMax: 7,
    mst: 0,
    ata: 0,
    evpMin: 25,
    evpMax: 30,
    lck: 0,
    efr: 0,
    eic: 10,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, eic: 10 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'shifta_merge',
    label: "Shifta Merge",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 16,
    requirement: "Level 16",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 2,
    dfpMax: 7,
    mst: 0,
    ata: 0,
    evpMin: 25,
    evpMax: 30,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 10,
    elt: 15,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 10, elt: 15 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'rafoie_merge',
    label: "Rafoie Merge",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 18,
    requirement: "Level 18",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 2,
    dfpMax: 7,
    mst: 0,
    ata: 0,
    evpMin: 25,
    evpMax: 30,
    lck: 0,
    efr: 15,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 15 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'rabarta_merge',
    label: "Rabarta Merge",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 19,
    requirement: "Level 19",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 2,
    dfpMax: 7,
    mst: 0,
    ata: 0,
    evpMin: 25,
    evpMax: 30,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 15,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, eth: 15 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'razonde_merge',
    label: "Razonde Merge",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 20,
    requirement: "Level 20",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 2,
    dfpMax: 7,
    mst: 0,
    ata: 0,
    evpMin: 25,
    evpMax: 30,
    lck: 0,
    efr: 0,
    eic: 15,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, eic: 15 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'red_merge',
    label: "Red Merge",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 24,
    requirement: "Level 24",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 2,
    dfpMax: 7,
    mst: 0,
    ata: 0,
    evpMin: 25,
    evpMax: 30,
    lck: 0,
    efr: 20,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 20 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'blue_merge',
    label: "Blue Merge",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 25,
    requirement: "Level 25",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 2,
    dfpMax: 7,
    mst: 0,
    ata: 0,
    evpMin: 25,
    evpMax: 30,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 20,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, eth: 20 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'yellow_merge',
    label: "Yellow Merge",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 26,
    requirement: "Level 26",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 2,
    dfpMax: 7,
    mst: 0,
    ata: 0,
    evpMin: 25,
    evpMax: 30,
    lck: 0,
    efr: 0,
    eic: 20,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, eic: 20 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'black_gear',
    label: "Black Gear",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 33,
    requirement: "Level 33",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 23,
    dfpMax: 28,
    mst: 0,
    ata: 0,
    evpMin: 80,
    evpMax: 85,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 10,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 10 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'angel_ring',
    label: "Angel Ring",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 40,
    requirement: "Level 40",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 40,
    dfpMax: 40,
    mst: 0,
    ata: 0,
    evpMin: 60,
    evpMax: 60,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 30,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, elt: 30 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'force_wall',
    label: "Force Wall",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 41,
    requirement: "Level 41",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 65,
    dfpMax: 75,
    mst: 20,
    ata: 0,
    evpMin: 140,
    evpMax: 150,
    lck: 0,
    efr: 15,
    eic: 20,
    eth: 18,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, mst: 20, efr: 15, eic: 20, eth: 18 },
    conditionalEffects: [],
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '010280',
  },
  {
    id: 'hunter_wall',
    label: "Hunter Wall",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 41,
    requirement: "Level 41",
    hp: 0,
    tp: 0,
    atp: 15,
    dfpMin: 70,
    dfpMax: 80,
    mst: 0,
    ata: 0,
    evpMin: 135,
    evpMax: 145,
    lck: 0,
    efr: 20,
    eic: 18,
    eth: 20,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, atp: 15, efr: 20, eic: 18, eth: 20 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal'],
    hex: '010280',
  },
  {
    id: 'ranger_wall',
    label: "Ranger Wall",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 41,
    requirement: "Level 41",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 70,
    dfpMax: 80,
    mst: 0,
    ata: 20,
    evpMin: 145,
    evpMax: 155,
    lck: 0,
    efr: 15,
    eic: 18,
    eth: 15,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, ata: 20, efr: 15, eic: 18, eth: 15 },
    conditionalEffects: [],
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010280',
  },
  {
    id: 'gods_shield_byakko',
    label: "Gods Shield \"Byakko\"",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 51,
    requirement: "Level 51",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 45,
    dfpMax: 45,
    mst: 0,
    ata: 0,
    evpMin: 80,
    evpMax: 80,
    lck: 0,
    efr: 10,
    eic: 10,
    eth: 30,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 10, eic: 10, eth: 30 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'gods_shield_genbu',
    label: "Gods Shield \"Genbu\"",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 51,
    requirement: "Level 51",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 45,
    dfpMax: 45,
    mst: 0,
    ata: 0,
    evpMin: 80,
    evpMax: 80,
    lck: 0,
    efr: 10,
    eic: 30,
    eth: 10,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 10, eic: 30, eth: 10 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'gods_shield_seiryu',
    label: "Gods Shield \"Seiryu\"",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 51,
    requirement: "Level 51",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 50,
    dfpMax: 50,
    mst: 0,
    ata: 0,
    evpMin: 100,
    evpMax: 100,
    lck: 0,
    efr: 20,
    eic: 20,
    eth: 20,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 20, eic: 20, eth: 20 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'gods_shield_suzaku',
    label: "Gods Shield \"Suzaku\"",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 51,
    requirement: "Level 51",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 50,
    dfpMax: 50,
    mst: 0,
    ata: 0,
    evpMin: 100,
    evpMax: 100,
    lck: 0,
    efr: 30,
    eic: 10,
    eth: 20,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 30, eic: 10, eth: 20 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'stink_shield',
    label: "Stink Shield",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 51,
    requirement: "Level 51",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 50,
    dfpMax: 125,
    mst: 0,
    ata: 0,
    evpMin: 55,
    evpMax: 130,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 20,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 20 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'weapons_copper_shield',
    label: "Weapons Copper Shield",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 55,
    requirement: "Level 55",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 24,
    dfpMax: 24,
    mst: 0,
    ata: 0,
    evpMin: 25,
    evpMax: 25,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'weapons_gold_shield',
    label: "Weapons Gold Shield",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 55,
    requirement: "Level 55",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 41,
    dfpMax: 41,
    mst: 0,
    ata: 0,
    evpMin: 100,
    evpMax: 100,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'weapons_silver_shield',
    label: "Weapons Silver Shield",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 55,
    requirement: "Level 55",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 35,
    dfpMax: 35,
    mst: 0,
    ata: 0,
    evpMin: 50,
    evpMax: 50,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'black_ring',
    label: "Black Ring",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 81,
    requirement: "Level 81",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 35,
    dfpMax: 40,
    mst: 0,
    ata: 0,
    evpMin: 130,
    evpMax: 135,
    lck: 0,
    efr: 5,
    eic: 5,
    eth: 5,
    edk: 5,
    elt: 5,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 5, eic: 5, eth: 5, edk: 5, elt: 5 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'blue_ring',
    label: "Blue Ring",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 81,
    requirement: "Level 81",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 35,
    dfpMax: 40,
    mst: 0,
    ata: 0,
    evpMin: 130,
    evpMax: 135,
    lck: 0,
    efr: 5,
    eic: 5,
    eth: 5,
    edk: 5,
    elt: 5,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 5, eic: 5, eth: 5, edk: 5, elt: 5 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'green_ring',
    label: "Green Ring",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 81,
    requirement: "Level 81",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 35,
    dfpMax: 40,
    mst: 0,
    ata: 0,
    evpMin: 130,
    evpMax: 135,
    lck: 0,
    efr: 5,
    eic: 5,
    eth: 5,
    edk: 5,
    elt: 5,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 5, eic: 5, eth: 5, edk: 5, elt: 5 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'purple_ring',
    label: "Purple Ring",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 81,
    requirement: "Level 81",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 35,
    dfpMax: 40,
    mst: 0,
    ata: 0,
    evpMin: 130,
    evpMax: 135,
    lck: 0,
    efr: 5,
    eic: 5,
    eth: 5,
    edk: 5,
    elt: 5,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 5, eic: 5, eth: 5, edk: 5, elt: 5 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'white_ring',
    label: "White Ring",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 81,
    requirement: "Level 81",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 35,
    dfpMax: 40,
    mst: 0,
    ata: 0,
    evpMin: 130,
    evpMax: 135,
    lck: 0,
    efr: 5,
    eic: 5,
    eth: 5,
    edk: 5,
    elt: 5,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 5, eic: 5, eth: 5, edk: 5, elt: 5 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'yellow_ring',
    label: "Yellow Ring",
    type: 'Shield',
    rarity: 9,
    requiredLevel: 81,
    requirement: "Level 81",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 35,
    dfpMax: 40,
    mst: 0,
    ata: 0,
    evpMin: 130,
    evpMax: 135,
    lck: 0,
    efr: 5,
    eic: 5,
    eth: 5,
    edk: 5,
    elt: 5,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 5, eic: 5, eth: 5, edk: 5, elt: 5 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'invisible_guard',
    label: "Invisible Guard",
    type: 'Shield',
    rarity: 10,
    requiredLevel: 17,
    requirement: "Level 17",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 15,
    dfpMax: 23,
    mst: 0,
    ata: 0,
    evpMin: 70,
    evpMax: 78,
    lck: 0,
    efr: 18,
    eic: 30,
    eth: 25,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 18, eic: 30, eth: 25 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'light_relief',
    label: "Light Relief",
    type: 'Shield',
    rarity: 10,
    requiredLevel: 17,
    requirement: "Level 17",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 20,
    dfpMax: 27,
    mst: 0,
    ata: 0,
    evpMin: 70,
    evpMax: 77,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 25,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 25 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 's_parts_ver116',
    label: "S-Parts ver1.16",
    type: 'Shield',
    rarity: 10,
    requiredLevel: 17,
    requirement: "Level 17",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 20,
    dfpMax: 28,
    mst: 0,
    ata: 0,
    evpMin: 60,
    evpMax: 68,
    lck: 0,
    efr: 15,
    eic: 30,
    eth: 15,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 15, eic: 30, eth: 15 },
    conditionalEffects: [],
    compatibleClasses: ['hucast', 'hucaseal', 'racast', 'racaseal'],
    hex: '010280',
  },
  {
    id: 's_parts_ver201',
    label: "S-Parts ver2.01",
    type: 'Shield',
    rarity: 10,
    requiredLevel: 17,
    requirement: "Level 17",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 25,
    dfpMax: 32,
    mst: 0,
    ata: 15,
    evpMin: 65,
    evpMax: 72,
    lck: 0,
    efr: 10,
    eic: 30,
    eth: 10,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, ata: 15, efr: 10, eic: 30, eth: 10 },
    conditionalEffects: [],
    compatibleClasses: ['hucast', 'hucaseal', 'racast', 'racaseal'],
    hex: '010280',
  },
  {
    id: 'sacred_guard',
    label: "Sacred Guard",
    type: 'Shield',
    rarity: 10,
    requiredLevel: 17,
    requirement: "Level 17",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 5,
    dfpMax: 13,
    mst: 0,
    ata: 0,
    evpMin: 15,
    evpMax: 23,
    lck: 0,
    efr: 20,
    eic: 18,
    eth: 22,
    edk: 0,
    elt: 15,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 20, eic: 18, eth: 22, elt: 15 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'anti_light_ring',
    label: "Anti-Light Ring",
    type: 'Shield',
    rarity: 10,
    requiredLevel: 30,
    requirement: "Level 30",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 90,
    dfpMax: 90,
    mst: 0,
    ata: 0,
    evpMin: 80,
    evpMax: 80,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 60,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, elt: 60 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'attribute_wall',
    label: "Attribute Wall",
    type: 'Shield',
    rarity: 10,
    requiredLevel: 41,
    requirement: "Level 41",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 75,
    dfpMax: 85,
    mst: 0,
    ata: 0,
    evpMin: 100,
    evpMax: 110,
    lck: 0,
    efr: 30,
    eic: 30,
    eth: 30,
    edk: 5,
    elt: 5,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 30, eic: 30, eth: 30, edk: 5, elt: 5 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'secret_gear',
    label: "Secret Gear",
    type: 'Shield',
    rarity: 10,
    requiredLevel: 41,
    requirement: "Level 41",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 75,
    dfpMax: 85,
    mst: 0,
    ata: 0,
    evpMin: 105,
    evpMax: 115,
    lck: 0,
    efr: 30,
    eic: 30,
    eth: 20,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 30, eic: 30, eth: 20 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'shield_of_delsaber',
    label: "Shield of Delsaber",
    type: 'Shield',
    rarity: 10,
    requiredLevel: 41,
    requirement: "Level 41",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 65,
    dfpMax: 72,
    mst: 0,
    ata: 0,
    evpMin: 115,
    evpMax: 122,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 25,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 25 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010280',
  },
  {
    id: 'union_guard',
    label: "Union Guard",
    type: 'Shield',
    rarity: 10,
    requiredLevel: 50,
    requirement: "Level 50",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 50,
    dfpMax: 50,
    mst: 0,
    ata: 0,
    evpMin: 0,
    evpMax: 200,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 5,
    elt: 5,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 5, elt: 5 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'combat_gear',
    label: "Combat Gear",
    type: 'Shield',
    rarity: 10,
    requiredLevel: 66,
    requirement: "Level 66",
    hp: 0,
    tp: 0,
    atp: 35,
    dfpMin: 0,
    dfpMax: 0,
    mst: 0,
    ata: 0,
    evpMin: 0,
    evpMax: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, atp: 35 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'custom_barrier_veroo',
    label: "Custom Barrier ver.OO",
    type: 'Shield',
    rarity: 10,
    requiredLevel: 66,
    requirement: "Level 66",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 65,
    dfpMax: 75,
    mst: 0,
    ata: 0,
    evpMin: 65,
    evpMax: 75,
    lck: 0,
    efr: 30,
    eic: 30,
    eth: 28,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 30, eic: 30, eth: 28 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'dbs_shield',
    label: "DB's Shield",
    type: 'Shield',
    rarity: 10,
    requiredLevel: 66,
    requirement: "Level 66",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 67,
    dfpMax: 77,
    mst: 0,
    ata: 0,
    evpMin: 67,
    evpMax: 77,
    lck: 0,
    efr: 25,
    eic: 25,
    eth: 30,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 25, eic: 25, eth: 30 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010280',
  },
  {
    id: 'flowens_shield',
    label: "Flowen's Shield",
    type: 'Shield',
    rarity: 10,
    requiredLevel: 66,
    requirement: "Level 66",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 62,
    dfpMax: 72,
    mst: 0,
    ata: 0,
    evpMin: 70,
    evpMax: 80,
    lck: 0,
    efr: 25,
    eic: 30,
    eth: 22,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 25, eic: 30, eth: 22 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010280',
  },
  {
    id: 'proto_regene_gear',
    label: "Proto Regene Gear",
    type: 'Shield',
    rarity: 10,
    requiredLevel: 66,
    requirement: "Level 66",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 40,
    dfpMax: 47,
    mst: 0,
    ata: 0,
    evpMin: 85,
    evpMax: 92,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'regene_gear_adv',
    label: "Regene Gear Adv.",
    type: 'Shield',
    rarity: 10,
    requiredLevel: 66,
    requirement: "Level 66",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 45,
    dfpMax: 52,
    mst: 0,
    ata: 0,
    evpMin: 90,
    evpMax: 97,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'regenerate_gear',
    label: "Regenerate Gear",
    type: 'Shield',
    rarity: 10,
    requiredLevel: 66,
    requirement: "Level 66",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 40,
    dfpMax: 47,
    mst: 0,
    ata: 0,
    evpMin: 85,
    evpMax: 92,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'anti_dark_ring',
    label: "Anti-Dark Ring",
    type: 'Shield',
    rarity: 10,
    requiredLevel: 80,
    requirement: "Level 80",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 20,
    dfpMax: 20,
    mst: 0,
    ata: 0,
    evpMin: 135,
    evpMax: 135,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 60,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 60 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'genpei',
    label: "Genpei",
    type: 'Shield',
    rarity: 10,
    requiredLevel: 80,
    requirement: "Level 80",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 158,
    dfpMax: 158,
    mst: 0,
    ata: 0,
    evpMin: 237,
    evpMax: 237,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'gratia',
    label: "Gratia",
    type: 'Shield',
    rarity: 10,
    requiredLevel: 101,
    requirement: "Level 101",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 130,
    dfpMax: 150,
    mst: 0,
    ata: 0,
    evpMin: 200,
    evpMax: 215,
    lck: 0,
    efr: 34,
    eic: 34,
    eth: 34,
    edk: 24,
    elt: 24,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 34, eic: 34, eth: 34, edk: 24, elt: 24 },
    conditionalEffects: [],
    compatibleClasses: ['hucast', 'hucaseal', 'racast', 'racaseal'],
    hex: '010280',
  },
  {
    id: 'regenerate_gear_bp',
    label: "Regenerate Gear B.P.",
    type: 'Shield',
    rarity: 10,
    requiredLevel: 101,
    requirement: "Level 101",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 90,
    dfpMax: 97,
    mst: 0,
    ata: 0,
    evpMin: 180,
    evpMax: 187,
    lck: 0,
    efr: 15,
    eic: 15,
    eth: 15,
    edk: 15,
    elt: 15,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 15, eic: 15, eth: 15, edk: 15, elt: 15 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'de_rol_le_shield',
    label: "De Rol Le Shield",
    type: 'Shield',
    rarity: 10,
    requiredLevel: 102,
    requirement: "Level 102",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 180,
    dfpMax: 255,
    mst: 0,
    ata: 0,
    evpMin: 120,
    evpMax: 195,
    lck: 0,
    efr: 5,
    eic: 20,
    eth: 15,
    edk: 0,
    elt: 20,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 5, eic: 20, eth: 15, elt: 20 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'ramar', 'ramarl', 'fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '010280',
  },
  {
    id: 'epsiguard',
    label: "Epsiguard",
    type: 'Shield',
    rarity: 10,
    requiredLevel: 102,
    requirement: "Level 102",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 120,
    dfpMax: 195,
    mst: 0,
    ata: 0,
    evpMin: 180,
    evpMax: 255,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: ['hucast', 'hucaseal', 'racast', 'racaseal'],
    hex: '010280',
  },
  {
    id: 'honeycomb_reflector',
    label: "Honeycomb Reflector",
    type: 'Shield',
    rarity: 10,
    requiredLevel: 102,
    requirement: "Level 102",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 110,
    dfpMax: 120,
    mst: 0,
    ata: 0,
    evpMin: 140,
    evpMax: 150,
    lck: 0,
    efr: 25,
    eic: 25,
    eth: 30,
    edk: 0,
    elt: 5,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 25, eic: 25, eth: 30, elt: 5 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'tripolic_shield',
    label: "Tripolic Shield",
    type: 'Shield',
    rarity: 10,
    requiredLevel: 102,
    requirement: "Level 102",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 95,
    dfpMax: 145,
    mst: 0,
    ata: 0,
    evpMin: 231,
    evpMax: 246,
    lck: 0,
    efr: 20,
    eic: 25,
    eth: 20,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 20, eic: 25, eth: 20 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'hunters_shell',
    label: "Hunter's Shell",
    type: 'Shield',
    rarity: 10,
    requiredLevel: 109,
    requirement: "Level 109",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 88,
    dfpMax: 138,
    mst: 0,
    ata: 0,
    evpMin: 222,
    evpMax: 237,
    lck: 0,
    efr: 22,
    eic: 27,
    eth: 28,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 22, eic: 27, eth: 28 },
    conditionalEffects: [],
    compatibleClasses: ['humar'],
    hex: '010280',
  },
  {
    id: 'kasami_bracer',
    label: "Kasami Bracer",
    type: 'Shield',
    rarity: 10,
    requiredLevel: 112,
    requirement: "Level 112",
    hp: 0,
    tp: 0,
    atp: 35,
    dfpMin: 96,
    dfpMax: 146,
    mst: 0,
    ata: 0,
    evpMin: 235,
    evpMax: 250,
    lck: 0,
    efr: 28,
    eic: 28,
    eth: 28,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, atp: 35, efr: 28, eic: 28, eth: 28 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal'],
    hex: '010280',
  },
  {
    id: 'tripolic_reflector',
    label: "Tripolic Reflector",
    type: 'Shield',
    rarity: 10,
    requiredLevel: 120,
    requirement: "Level 120",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 95,
    dfpMax: 145,
    mst: 0,
    ata: 0,
    evpMin: 235,
    evpMax: 250,
    lck: 0,
    efr: 22,
    eic: 22,
    eth: 28,
    edk: 7,
    elt: 7,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 22, eic: 22, eth: 28, edk: 7, elt: 7 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'yata_mirror',
    label: "Yata Mirror",
    type: 'Shield',
    rarity: 10,
    requiredLevel: 120,
    requirement: "Level 120",
    hp: 0,
    tp: 0,
    atp: 35,
    dfpMin: 40,
    dfpMax: 60,
    mst: 0,
    ata: 0,
    evpMin: 200,
    evpMax: 225,
    lck: 0,
    efr: 12,
    eic: 12,
    eth: 12,
    edk: 0,
    elt: 25,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, atp: 35, efr: 12, eic: 12, eth: 12, elt: 25 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010280',
  },
  {
    id: 'standstill_shield',
    label: "Standstill Shield",
    type: 'Shield',
    rarity: 10,
    requiredLevel: 125,
    requirement: "Level 125",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 163,
    dfpMax: 213,
    mst: 0,
    ata: 0,
    evpMin: 175,
    evpMax: 190,
    lck: 0,
    efr: 20,
    eic: 20,
    eth: 27,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 20, eic: 20, eth: 27 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010280',
  },
  {
    id: 'black_gauntlets',
    label: "Black Gauntlets",
    type: 'Shield',
    rarity: 10,
    requiredLevel: 131,
    requirement: "Level 131",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 120,
    dfpMax: 170,
    mst: 0,
    ata: 0,
    evpMin: 200,
    evpMax: 215,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 35,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 35 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '010280',
  },
  {
    id: 'three_seals',
    label: "Three Seals",
    type: 'Shield',
    rarity: 11,
    requiredLevel: 33,
    requirement: "Level 33",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 33,
    dfpMax: 36,
    mst: 0,
    ata: 0,
    evpMin: 33,
    evpMax: 36,
    lck: 0,
    efr: 33,
    eic: 33,
    eth: 33,
    edk: 33,
    elt: 33,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 33, eic: 33, eth: 33, edk: 33, elt: 33 },
    conditionalEffects: [],
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '010280',
  },
  {
    id: 'df_shield',
    label: "DF Shield",
    type: 'Shield',
    rarity: 11,
    requiredLevel: 100,
    requirement: "Level 100",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 60,
    dfpMax: 145,
    mst: 0,
    ata: 0,
    evpMin: 170,
    evpMax: 195,
    lck: 0,
    efr: 10,
    eic: 20,
    eth: 16,
    edk: 14,
    elt: 14,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 10, eic: 20, eth: 16, edk: 14, elt: 14 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'gods_shield_kouryu',
    label: "Gods Shield \"Kouryu\"",
    type: 'Shield',
    rarity: 11,
    requiredLevel: 101,
    requirement: "Level 101",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 95,
    dfpMax: 95,
    mst: 0,
    ata: 0,
    evpMin: 180,
    evpMax: 180,
    lck: 0,
    efr: 40,
    eic: 40,
    eth: 40,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 40, eic: 40, eth: 40 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'rupika',
    label: "Rupika",
    type: 'Shield',
    rarity: 11,
    requiredLevel: 101,
    requirement: "Level 101",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 120,
    dfpMax: 130,
    mst: 0,
    ata: 0,
    evpMin: 180,
    evpMax: 200,
    lck: 0,
    efr: 12,
    eic: 12,
    eth: 12,
    edk: 25,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 12, eic: 12, eth: 12, edk: 25 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'striker_plus',
    label: "Striker Plus",
    type: 'Shield',
    rarity: 11,
    requiredLevel: 112,
    requirement: "Level 112",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 80,
    dfpMax: 90,
    mst: 0,
    ata: 0,
    evpMin: 200,
    evpMax: 205,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010280',
  },
  {
    id: 'secure_feet',
    label: "Secure Feet",
    type: 'Shield',
    rarity: 11,
    requiredLevel: 120,
    requirement: "Level 120",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 83,
    dfpMax: 133,
    mst: 0,
    ata: 0,
    evpMin: 230,
    evpMax: 245,
    lck: 0,
    efr: 20,
    eic: 20,
    eth: 20,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 20, eic: 20, eth: 20 },
    conditionalEffects: [],
    compatibleClasses: ['ramar', 'ramarl'],
    hex: '010280',
  },
  {
    id: 'safety_heart',
    label: "Safety Heart",
    type: 'Shield',
    rarity: 11,
    requiredLevel: 123,
    requirement: "Level 123",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 106,
    dfpMax: 156,
    mst: 0,
    ata: 0,
    evpMin: 248,
    evpMax: 263,
    lck: 0,
    efr: 25,
    eic: 25,
    eth: 25,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 25, eic: 25, eth: 25 },
    conditionalEffects: [],
    compatibleClasses: ['hunewearl', 'hucaseal', 'ramarl', 'racaseal', 'fomarl', 'fonewearl'],
    hex: '010280',
  },
  {
    id: 'ricos_earring',
    label: "Rico's Earring",
    type: 'Shield',
    rarity: 11,
    requiredLevel: 133,
    requirement: "Level 133",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 96,
    dfpMax: 181,
    mst: 0,
    ata: 0,
    evpMin: 237,
    evpMax: 262,
    lck: 0,
    efr: 15,
    eic: 15,
    eth: 15,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 15, eic: 15, eth: 15 },
    conditionalEffects: [],
    compatibleClasses: ['hunewearl', 'hucaseal', 'ramarl', 'racaseal', 'fomarl', 'fonewearl'],
    hex: '010280',
  },
  {
    id: 'ricos_glasses',
    label: "Rico's Glasses",
    type: 'Shield',
    rarity: 11,
    requiredLevel: 148,
    requirement: "Level 148",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 1,
    dfpMax: 1,
    mst: 0,
    ata: 0,
    evpMin: 1,
    evpMax: 1,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: ['fomarl'],
    hex: '010280',
  },
  {
    id: 'red_ring',
    label: "Red Ring",
    type: 'Shield',
    rarity: 11,
    requiredLevel: 180,
    requirement: "Level 180",
    hp: 0,
    tp: 0,
    atp: 20,
    dfpMin: 150,
    dfpMax: 235,
    mst: 20,
    ata: 20,
    evpMin: 232,
    evpMax: 257,
    lck: 20,
    efr: 30,
    eic: 30,
    eth: 30,
    edk: 5,
    elt: 5,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, atp: 20, mst: 20, ata: 20, lck: 20, efr: 30, eic: 30, eth: 30, edk: 5, elt: 5 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'ragol_ring',
    label: "Ragol Ring",
    type: 'Shield',
    rarity: 12,
    requiredLevel: 101,
    requirement: "Level 101",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 105,
    dfpMax: 105,
    mst: 0,
    ata: 0,
    evpMin: 130,
    evpMax: 130,
    lck: 0,
    efr: 10,
    eic: 10,
    eth: 10,
    edk: 10,
    elt: 10,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 10, eic: 10, eth: 10, edk: 10, elt: 10 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  },
  {
    id: 'from_the_depths',
    label: "From the Depths",
    type: 'Shield',
    rarity: 12,
    requiredLevel: 150,
    requirement: "Level 150",
    hp: 0,
    tp: 0,
    atp: 0,
    dfpMin: 160,
    dfpMax: 160,
    mst: 0,
    ata: 0,
    evpMin: 240,
    evpMax: 240,
    lck: 0,
    efr: 20,
    eic: 40,
    eth: 32,
    edk: 28,
    elt: 28,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 20, eic: 40, eth: 32, edk: 28, elt: 28 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010280',
  }
]
