import type { CharacterUnitOption } from './index.js'

const ZERO_CHARACTER_STAT_BONUSES = {
  hp: 0,
  tp: 0,
  atp: 0,
  dfp: 0,
  mst: 0,
  ata: 0,
  evp: 0,
  lck: 0,
  efr: 0,
  eic: 0,
  eth: 0,
  edk: 0,
  elt: 0,
}

const RANGED_WEAPON_TYPES = ['Handgun', 'Rifle', 'Mechgun', 'Shot', 'Launcher']

const STATUS_SPECIAL_WEAPON_LABELS = ['Chaos', 'Blizzard', 'Blizzard (Reduced)', 'Arrest']

const INSTANT_KILL_SPECIAL_WEAPON_LABELS = ['Hell', 'Hell (Reduced)', 'Dark', 'Dark (Reduced)']

const PROOF_OF_SWORD_SAINT_WEAPON_LABELS = [
  'Ancient Saber',
  "Delsaber's Buster",
  'Durandal',
  'Elysion',
  'Excalibur',
  'Flamberge',
  'Galatine',
  'Kaladbolg',
  'Kusanagi',
  'Lavis Cannon',
  'Red Saber',
  'Guren',
  'Kamui',
  'Murasame',
  'Orotiagito',
  'Raikiri',
  'Sange',
  'Shichishito',
  'Shouren',
  'Yamigarasu',
  'Yasha',
  'Asuka',
  'Jizai',
  'Musashi',
  'Sange & Yasha',
  'Yamato',
  'Two Kamui',
]

export const ADDITIONAL_CHARACTER_UNIT_OPTIONS: CharacterUnitOption[] = [
  {
    id: 'digger_hp',
    label: "Digger/HP",
    type: 'Unit',
    hp: 10,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, hp: 10 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'knight_power',
    label: "Knight/Power",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 5,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, atp: 5 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'magician_tp',
    label: "Magician/TP",
    type: 'Unit',
    hp: 0,
    tp: 10,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, tp: 10 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'marksman_arm',
    label: "Marksman/Arm",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 3,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, ata: 3 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'priest_mind',
    label: "Priest/Mind",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 5,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, mst: 5 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'ramar', 'ramarl', 'fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '000000',
  },
  {
    id: 'resist_cold',
    label: "Resist/Cold",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 5,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, eic: 5 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'resist_fire',
    label: "Resist/Fire",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 5,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 5 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'resist_shock',
    label: "Resist/Shock",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 5,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, eth: 5 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'thief_legs',
    label: "Thief/Legs",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 10,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, evp: 10 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'warrior_body',
    label: "Warrior/Body",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 10,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, dfp: 10 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'general_arm',
    label: "General/Arm",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 5,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, ata: 5 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'general_body',
    label: "General/Body",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 20,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, dfp: 20 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'general_legs',
    label: "General/Legs",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 20,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, evp: 20 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'general_mind',
    label: "General/Mind",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 10,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, mst: 10 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'ramar', 'ramarl', 'fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '000000',
  },
  {
    id: 'general_power',
    label: "General/Power",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 10,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, atp: 10 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'resist_dark',
    label: "Resist/Dark",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 5,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 5 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'resist_flame',
    label: "Resist/Flame",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 10,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 10 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'resist_freeze',
    label: "Resist/Freeze",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 10,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, eic: 10 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'resist_light',
    label: "Resist/Light",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 5,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, elt: 5 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'resist_thunder',
    label: "Resist/Thunder",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 10,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, eth: 10 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'general_hp',
    label: "General/HP",
    type: 'Unit',
    hp: 20,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, hp: 20 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'general_tp',
    label: "General/TP",
    type: 'Unit',
    hp: 0,
    tp: 20,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, tp: 20 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'hp_restorate',
    label: "HP/Restorate",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'pb_amplifier',
    label: "PB/Amplifier",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'resist_evil',
    label: "Resist/Evil",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 10,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 10 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'resist_saint',
    label: "Resist/Saint",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 10,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, elt: 10 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'tp_restorate',
    label: "TP/Restorate",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'ramar', 'ramarl', 'fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '000000',
  },
  {
    id: 'angel_mind',
    label: "Angel/Mind",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 15,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, mst: 15 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'ramar', 'ramarl', 'fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '000000',
  },
  {
    id: 'elf_arm',
    label: "Elf/Arm",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 7,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, ata: 7 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '01030A',
  },
  {
    id: 'elf_legs',
    label: "Elf/Legs",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 30,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, evp: 30 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'metal_body',
    label: "Metal/Body",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 30,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, dfp: 30 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'ogre_power',
    label: "Ogre/Power",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 15,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, atp: 15 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '010302',
  },
  {
    id: 'resist_blizzard',
    label: "Resist/Blizzard",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 15,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, eic: 15 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'resist_burning',
    label: "Resist/Burning",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 15,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 15 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'resist_devil',
    label: "Resist/Devil",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 15,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, edk: 15 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'resist_storm',
    label: "Resist/Storm",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 15,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, eth: 15 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'angel_tp',
    label: "Angel/TP",
    type: 'Unit',
    hp: 0,
    tp: 30,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, tp: 30 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'dragon_hp',
    label: "Dragon/HP",
    type: 'Unit',
    hp: 40,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, hp: 40 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'general_battle',
    label: "General/Battle",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [{
      requirements: {},
      bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
      weaponAtpMultiplierPercent: 0,
      attackSpeedPercent: 5,
    }],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'hp_generate',
    label: "HP/Generate",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'pb_generate',
    label: "PB/Generate",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'resist_holy',
    label: "Resist/Holy",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 15,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, elt: 15 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'tp_generate',
    label: "TP/Generate",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'ramar', 'ramarl', 'fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '000000',
  },
  {
    id: 'wizard_technique',
    label: "Wizard/Technique",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [{
      requirements: {},
      bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
      weaponAtpMultiplierPercent: 0,
      techniqueLevelBonus: 1,
    }],
    compatibleClasses: ['humar', 'hunewearl', 'ramar', 'ramarl', 'fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '000000',
  },
  {
    id: 'all_resist',
    label: "All/Resist",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 3,
    eic: 3,
    eth: 3,
    edk: 3,
    elt: 3,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 3, eic: 3, eth: 3, edk: 3, elt: 3 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'angel_luck',
    label: "Angel/Luck",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 5,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, lck: 5 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'master_ability',
    label: "Master/Ability",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 5,
    dfp: 5,
    mst: 5,
    ata: 0.5,
    evp: 5,
    lck: 5,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, atp: 5, dfp: 5, mst: 5, ata: 0.5, evp: 5, lck: 5 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'super_resist',
    label: "Super/Resist",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 6,
    eic: 6,
    eth: 6,
    edk: 6,
    elt: 6,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 6, eic: 6, eth: 6, edk: 6, elt: 6 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'cure_confuse',
    label: "Cure/Confuse",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'cure_freeze',
    label: "Cure/Freeze",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'cure_paralysis',
    label: "Cure/Paralysis",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'ramar', 'ramarl', 'fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '000000',
  },
  {
    id: 'cure_poison',
    label: "Cure/Poison",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'ramar', 'ramarl', 'fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '000000',
  },
  {
    id: 'cure_shock',
    label: "Cure/Shock",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'cure_slow',
    label: "Cure/Slow",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'devil_battle',
    label: "Devil/Battle",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [{
      requirements: {},
      bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
      weaponAtpMultiplierPercent: 0,
      attackSpeedPercent: 10,
    }],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'devil_technique',
    label: "Devil/Technique",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [{
      requirements: {},
      bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
      weaponAtpMultiplierPercent: 0,
      techniqueLevelBonus: 2,
    }],
    compatibleClasses: ['humar', 'hunewearl', 'ramar', 'ramarl', 'fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '000000',
  },
  {
    id: 'hp_revival',
    label: "HP/Revival",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'pb_create',
    label: "PB/Create",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'tp_revival',
    label: "TP/Revival",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'ramar', 'ramarl', 'fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '000000',
  },
  {
    id: 'friend_ring',
    label: "Friend Ring",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'hero_ability',
    label: "Hero/Ability",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 10,
    dfp: 10,
    mst: 10,
    ata: 1,
    evp: 10,
    lck: 10,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, atp: 10, dfp: 10, mst: 10, ata: 1, evp: 10, lck: 10 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'yasakani_magatama',
    label: "Yasakani Magatama",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [
      {
            requirements: { weaponLabels: ["Kusanagi"] },
            bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, ata: 30 },
            weaponAtpMultiplierPercent: 0,
          }
    ],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '000000',
  },
  {
    id: 'adept',
    label: "Adept",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 10,
    dfp: 10,
    mst: 10,
    ata: 21,
    evp: 10,
    lck: 10,
    efr: 6,
    eic: 6,
    eth: 6,
    edk: 6,
    elt: 6,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, atp: 10, dfp: 10, mst: 10, ata: 21, evp: 10, lck: 10, efr: 6, eic: 6, eth: 6, edk: 6, elt: 6 },
    conditionalEffects: [{
      requirements: {},
      bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
      weaponAtpMultiplierPercent: 0,
      tpCostModifierPercent: -25,
    }],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'divine_protection',
    label: "Divine Protection",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'god_ability',
    label: "God/Ability",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 20,
    dfp: 20,
    mst: 20,
    ata: 2,
    evp: 20,
    lck: 20,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, atp: 20, dfp: 20, mst: 20, ata: 2, evp: 20, lck: 20 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'god_arm',
    label: "God/Arm",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 15,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, ata: 15 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'god_battle',
    label: "God/Battle",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [{
      requirements: {},
      bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
      weaponAtpMultiplierPercent: 0,
      attackSpeedPercent: 20,
    }],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'god_body',
    label: "God/Body",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 50,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, dfp: 50 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'god_hp',
    label: "God/HP",
    type: 'Unit',
    hp: 80,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, hp: 80 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'god_legs',
    label: "God/Legs",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 50,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, evp: 50 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'god_luck',
    label: "God/Luck",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 30,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, lck: 30 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'god_mind',
    label: "God/Mind",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 40,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, mst: 40 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'ramar', 'ramarl', 'fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '000000',
  },
  {
    id: 'god_power',
    label: "God/Power",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 50,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, atp: 50 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'god_technique',
    label: "God/Technique",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [{
      requirements: {},
      bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
      weaponAtpMultiplierPercent: 0,
      techniqueLevelBonus: 3,
    }],
    compatibleClasses: ['humar', 'hunewearl', 'ramar', 'ramarl', 'fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '000000',
  },
  {
    id: 'god_tp',
    label: "God/TP",
    type: 'Unit',
    hp: 0,
    tp: 80,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, tp: 80 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'heavenly_ability',
    label: "Heavenly/Ability",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 25,
    dfp: 25,
    mst: 25,
    ata: 2.5,
    evp: 25,
    lck: 25,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, atp: 25, dfp: 25, mst: 25, ata: 2.5, evp: 25, lck: 25 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'centurion_ability',
    label: "Centurion/Ability",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 30,
    dfp: 30,
    mst: 30,
    ata: 3,
    evp: 30,
    lck: 30,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, atp: 30, dfp: 30, mst: 30, ata: 3, evp: 30, lck: 30 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'heavenly_arms',
    label: "Heavenly/Arms",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 25,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, ata: 25 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'heavenly_battle',
    label: "Heavenly/Battle",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [{
      requirements: {},
      bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
      weaponAtpMultiplierPercent: 0,
      attackSpeedPercent: 40,
    }],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'heavenly_body',
    label: "Heavenly/Body",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 55,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, dfp: 55 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'heavenly_hp',
    label: "Heavenly/HP",
    type: 'Unit',
    hp: 100,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, hp: 100 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'heavenly_legs',
    label: "Heavenly/Legs",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 55,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, evp: 55 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'heavenly_luck',
    label: "Heavenly/Luck",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 40,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, lck: 40 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'heavenly_mind',
    label: "Heavenly/Mind",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 45,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, mst: 45 },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'ramar', 'ramarl', 'fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '000000',
  },
  {
    id: 'heavenly_power',
    label: "Heavenly/Power",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 55,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, atp: 55 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'heavenly_resist',
    label: "Heavenly/Resist",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 12,
    eic: 12,
    eth: 12,
    edk: 12,
    elt: 12,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 12, eic: 12, eth: 12, edk: 12, elt: 12 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'heavenly_technique',
    label: "Heavenly/Technique",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [{
      requirements: {},
      bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
      weaponAtpMultiplierPercent: 0,
      techniqueLevelBonus: 4,
    }],
    compatibleClasses: ['humar', 'hunewearl', 'ramar', 'ramarl', 'fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '000000',
  },
  {
    id: 'heavenly_tp',
    label: "Heavenly/TP",
    type: 'Unit',
    hp: 0,
    tp: 100,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, tp: 100 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'hp_resurrection',
    label: "HP/Resurrection",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'limiter',
    label: "Limiter",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: -30,
    dfp: -30,
    mst: -30,
    ata: -13,
    evp: -30,
    lck: -30,
    efr: -10,
    eic: -10,
    eth: -10,
    edk: -10,
    elt: -10,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, atp: -30, dfp: -30, mst: -30, ata: -13, evp: -30, lck: -30, efr: -10, eic: -10, eth: -10, edk: -10, elt: -10 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'pb_increase',
    label: "PB/Increase",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'perfect_resist',
    label: "Perfect/Resist",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 9,
    eic: 9,
    eth: 9,
    edk: 9,
    elt: 9,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, efr: 9, eic: 9, eth: 9, edk: 9, elt: 9 },
    conditionalEffects: [],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'proof_of_sword_saint',
    label: "Proof of Sword-Saint",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [{
      requirements: { weaponLabels: PROOF_OF_SWORD_SAINT_WEAPON_LABELS },
      bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, dfp: -20, ata: 30, evp: 60 },
      weaponAtpMultiplierPercent: 0,
    }],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal'],
    hex: '000000',
  },
  {
    id: 'smartlink',
    label: "Smartlink",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [{
      requirements: { weaponTypes: RANGED_WEAPON_TYPES },
      bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
      weaponAtpMultiplierPercent: 0,
      ignoresRangedAccuracyPenalty: true,
    }],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '000000',
  },
  {
    id: 'swordsman_lore',
    label: "Swordsman Lore",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal'],
    hex: '000000',
  },
  {
    id: 'tp_resurrection',
    label: "TP/Resurrection",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [],
    compatibleClasses: ['humar', 'hunewearl', 'ramar', 'ramarl', 'fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '000000',
  },
  {
    id: 'v101',
    label: "V101",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 15,
    dfp: 15,
    mst: 15,
    ata: 1.5,
    evp: 15,
    lck: 15,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES, atp: 15, dfp: 15, mst: 15, ata: 1.5, evp: 15, lck: 15 },
    conditionalEffects: [{
      requirements: {},
      bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
      weaponAtpMultiplierPercent: 0,
      attackSpeedPercent: 40,
    }],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'v501',
    label: "V501",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [
      {
        requirements: { weaponSpecials: STATUS_SPECIAL_WEAPON_LABELS },
        bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
        weaponAtpMultiplierPercent: 0,
        statusSpecialSuccessRatePercent: 50,
      },
      {
        requirements: { weaponSpecials: INSTANT_KILL_SPECIAL_WEAPON_LABELS },
        bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
        weaponAtpMultiplierPercent: 0,
        instantKillSpecialSuccessRatePercent: 50,
      },
    ],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'v502',
    label: "V502",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [
      {
        requirements: { weaponSpecials: STATUS_SPECIAL_WEAPON_LABELS },
        bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
        weaponAtpMultiplierPercent: 0,
        statusSpecialSuccessRatePercent: 50,
      },
      {
        requirements: { weaponSpecials: INSTANT_KILL_SPECIAL_WEAPON_LABELS },
        bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
        weaponAtpMultiplierPercent: 0,
        instantKillSpecialSuccessRatePercent: 100,
      },
    ],
    compatibleClasses: 'all',
    hex: '000000',
  },
  {
    id: 'v801',
    label: "V801",
    type: 'Unit',
    hp: 0,
    tp: 0,
    atp: 0,
    dfp: 0,
    mst: 0,
    ata: 0,
    evp: 0,
    lck: 0,
    efr: 0,
    eic: 0,
    eth: 0,
    edk: 0,
    elt: 0,
    bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
    conditionalEffects: [{
      requirements: {},
      bonuses: { ...ZERO_CHARACTER_STAT_BONUSES },
      weaponAtpMultiplierPercent: 0,
      reducesTechniqueChargeTime: true,
      reducesTechniqueCastTime: true,
    }],
    compatibleClasses: ['humar', 'hunewearl', 'ramar', 'ramarl', 'fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '000000',
  }
]
