import type { CharacterConditionalEffect, CharacterWeaponOption } from './index.js'

const ZERO_WEAPON_STAT_BONUSES = {
  hp: 0,
  tp: 0,
  atp: 0,
  dfp: 0,
  mst: 0,
  ata: 0,
  evp: 0,
  lck: 0,
  efr: 0,
  eic: 0,
  eth: 0,
  edk: 0,
  elt: 0,
}

const KATANA_WEAPON_DEFAULTS = {
  type: 'Katana',
  bonuses: { ...ZERO_WEAPON_STAT_BONUSES },
  conditionalEffects: [] as CharacterConditionalEffect[],
  compatibleClasses: 'all' as const,
  hardDistance: 14,
  hardAngle: 26,
  veryHardDistance: 18,
  veryHardAngle: 26,
}

const TWIN_SWORD_WEAPON_DEFAULTS = {
  type: 'Twin Sword',
  bonuses: { ...ZERO_WEAPON_STAT_BONUSES },
  conditionalEffects: [] as CharacterConditionalEffect[],
  compatibleClasses: 'all' as const,
  hardDistance: 18,
  hardAngle: 26,
  veryHardDistance: 18,
  veryHardAngle: 26,
}

const FIST_WEAPON_DEFAULTS = {
  type: 'Fist',
  bonuses: { ...ZERO_WEAPON_STAT_BONUSES },
  conditionalEffects: [] as CharacterConditionalEffect[],
  compatibleClasses: 'all' as const,
  hardDistance: 14,
  hardAngle: 30,
  veryHardDistance: 18,
  veryHardAngle: 26,
}

const HANDGUN_WEAPON_DEFAULTS = {
  type: 'Handgun',
  bonuses: { ...ZERO_WEAPON_STAT_BONUSES },
  conditionalEffects: [] as CharacterConditionalEffect[],
  compatibleClasses: 'all' as const,
  hardDistance: 170,
  hardAngle: 10,
  veryHardDistance: 30,
  veryHardAngle: 36,
}

const RIFLE_WEAPON_DEFAULTS = {
  type: 'Rifle',
  bonuses: { ...ZERO_WEAPON_STAT_BONUSES },
  conditionalEffects: [] as CharacterConditionalEffect[],
  compatibleClasses: 'all' as const,
  hardDistance: 210,
  hardAngle: 10,
  veryHardDistance: 30,
  veryHardAngle: 36,
}

const MECHGUN_WEAPON_DEFAULTS = {
  type: 'Mechgun',
  bonuses: { ...ZERO_WEAPON_STAT_BONUSES },
  conditionalEffects: [] as CharacterConditionalEffect[],
  compatibleClasses: 'all' as const,
  hardDistance: 85,
  hardAngle: 10,
  veryHardDistance: 30,
  veryHardAngle: 36,
}

const SHOT_WEAPON_DEFAULTS = {
  type: 'Shot',
  bonuses: { ...ZERO_WEAPON_STAT_BONUSES },
  conditionalEffects: [] as CharacterConditionalEffect[],
  compatibleClasses: 'all' as const,
  hardDistance: 130,
  hardAngle: 45,
  veryHardDistance: 30,
  veryHardAngle: 36,
}

const LAUNCHER_WEAPON_DEFAULTS = {
  type: 'Launcher',
  bonuses: { ...ZERO_WEAPON_STAT_BONUSES },
  conditionalEffects: [] as CharacterConditionalEffect[],
  compatibleClasses: 'all' as const,
  hardDistance: 170,
  hardAngle: 10,
  veryHardDistance: 15,
  veryHardAngle: 26,
}

const CANE_WEAPON_DEFAULTS = {
  type: 'Cane',
  bonuses: { ...ZERO_WEAPON_STAT_BONUSES },
  conditionalEffects: [] as CharacterConditionalEffect[],
  compatibleClasses: 'all' as const,
  hardDistance: 14,
  hardAngle: 26,
  veryHardDistance: 18,
  veryHardAngle: 26,
}

const ROD_WEAPON_DEFAULTS = {
  type: 'Rod',
  bonuses: { ...ZERO_WEAPON_STAT_BONUSES },
  conditionalEffects: [] as CharacterConditionalEffect[],
  compatibleClasses: 'all' as const,
  hardDistance: 17,
  hardAngle: 27,
  veryHardDistance: 18,
  veryHardAngle: 27,
}

const WAND_WEAPON_DEFAULTS = {
  type: 'Wand',
  bonuses: { ...ZERO_WEAPON_STAT_BONUSES },
  conditionalEffects: [] as CharacterConditionalEffect[],
  compatibleClasses: 'all' as const,
  hardDistance: 13,
  hardAngle: 26,
  veryHardDistance: 18,
  veryHardAngle: 26,
}

const CARD_WEAPON_DEFAULTS = {
  type: 'Card',
  bonuses: { ...ZERO_WEAPON_STAT_BONUSES },
  conditionalEffects: [] as CharacterConditionalEffect[],
  compatibleClasses: 'all' as const,
  hardDistance: 150,
  hardAngle: 26,
  veryHardDistance: 30,
  veryHardAngle: 26,
}

export const ADDITIONAL_CHARACTER_WEAPON_OPTIONS: CharacterWeaponOption[] = [
// --- KATANAS ---
  {
    id: 'akikos_frying_pan',
    label: "Akiko's Frying Pan",
    requirement: "250 ATP",
    maxGrind: 0,
    special: "Mind",
    atpMin: 230,
    atpMax: 250,
    ata: 40,
    ...KATANA_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, mst: 30 },
    hex: '000800',
  },
  {
    id: 'murasame',
    label: "Murasame",
    requirement: "350 ATP",
    maxGrind: 0,
    special: "Dim",
    atpMin: 420,
    atpMax: 435,
    ata: 49,
    ...KATANA_WEAPON_DEFAULTS,
    hex: '000800',
  },
  {
    id: 'harisen_battle_fan',
    label: "Harisen Battle Fan",
    requirement: "412 ATP",
    maxGrind: 0,
    special: "Seize",
    atpMin: 280,
    atpMax: 310,
    ata: 40,
    ...KATANA_WEAPON_DEFAULTS,
    hex: '000800',
  },
  {
    id: 'toy_hammer',
    label: "Toy Hammer",
    requirement: "412 ATP",
    maxGrind: 0,
    special: "Berserk",
    atpMin: 1,
    atpMax: 400,
    ata: 1,
    ...KATANA_WEAPON_DEFAULTS,
    hex: '000800',
  },
  {
    id: 'agito_1977',
    label: "Agito (1977)",
    requirement: "510 ATP",
    maxGrind: 50,
    special: "Dim",
    atpMin: 450,
    atpMax: 460,
    ata: 48,
    ...KATANA_WEAPON_DEFAULTS,
    conditionalEffects: [
      {
        requirements: { armorLabels: ["Samurai Armor"] },
        bonuses: { ...ZERO_WEAPON_STAT_BONUSES, ata: 20 },
        weaponAtpMultiplierPercent: 30,
      },
    ],
    hex: '000800',
  },
  {
    id: 'agito_1980',
    label: "Agito (1980)",
    requirement: "500 ATP",
    maxGrind: 40,
    special: "Dim",
    atpMin: 455,
    atpMax: 460,
    ata: 51,
    ...KATANA_WEAPON_DEFAULTS,
    conditionalEffects: [
      {
        requirements: { armorLabels: ["Samurai Armor"] },
        bonuses: { ...ZERO_WEAPON_STAT_BONUSES, ata: 20 },
        weaponAtpMultiplierPercent: 30,
      },
    ],
    hex: '000800',
  },
  {
    id: 'agito_1983',
    label: "Agito (1983)",
    requirement: "500 ATP",
    maxGrind: 45,
    special: "Dim",
    atpMin: 200,
    atpMax: 500,
    ata: 47,
    ...KATANA_WEAPON_DEFAULTS,
    conditionalEffects: [
      {
        requirements: { armorLabels: ["Samurai Armor"] },
        bonuses: { ...ZERO_WEAPON_STAT_BONUSES, ata: 20 },
        weaponAtpMultiplierPercent: 30,
      },
    ],
    hex: '000800',
  },
  {
    id: 'agito_1991',
    label: "Agito (1991)",
    requirement: "350 ATP",
    maxGrind: 9,
    special: "Dim",
    atpMin: 400,
    atpMax: 410,
    ata: 45,
    ...KATANA_WEAPON_DEFAULTS,
    conditionalEffects: [
      {
        requirements: { armorLabels: ["Samurai Armor"] },
        bonuses: { ...ZERO_WEAPON_STAT_BONUSES, ata: 20 },
        weaponAtpMultiplierPercent: 30,
      },
    ],
    hex: '000800',
  },
  {
    id: 'agito_2001',
    label: "Agito (2001)",
    requirement: "356 ATP",
    maxGrind: 9,
    special: "Dim",
    atpMin: 400,
    atpMax: 430,
    ata: 40,
    ...KATANA_WEAPON_DEFAULTS,
    conditionalEffects: [
      {
        requirements: { armorLabels: ["Samurai Armor"] },
        bonuses: { ...ZERO_WEAPON_STAT_BONUSES, ata: 20 },
        weaponAtpMultiplierPercent: 30,
      },
    ],
    hex: '000800',
  },
  {
    id: 'shichishito',
    label: "Shichishito",
    requirement: "550 ATP",
    maxGrind: 0,
    special: "Dim",
    atpMin: 500,
    atpMax: 560,
    ata: 40,
    ...KATANA_WEAPON_DEFAULTS,
    hex: '000800',
  },
  {
    id: 'raikiri',
    label: "Raikiri",
    requirement: "580 ATP",
    maxGrind: 0,
    special: "See Notes",
    atpMin: 550,
    atpMax: 560,
    ata: 30,
    ...KATANA_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, dfp: -10, evp: -10, lck: -10 },
    hex: '000800',
  },
  {
    id: 'sange',
    label: "Sange",
    requirement: "650 ATP",
    maxGrind: 0,
    special: "Fill",
    atpMin: 500,
    atpMax: 550,
    ata: 50,
    ...KATANA_WEAPON_DEFAULTS,
    conditionalEffects: [
      {
        requirements: { armorLabels: ["Blue Odoshi Violet Nimaidou"] },
        bonuses: { ...ZERO_WEAPON_STAT_BONUSES, atp: 100, ata: 10 },
        weaponAtpMultiplierPercent: 0,
      },
    ],
    hex: '000800',
  },
  {
    id: 'yamigarasu',
    label: "Yamigarasu",
    requirement: "680 ATP",
    maxGrind: 0,
    special: "Hell",
    atpMin: 580,
    atpMax: 650,
    ata: 53,
    ...KATANA_WEAPON_DEFAULTS,
    hex: '000800',
  },
  {
    id: 'kamui',
    label: "Kamui",
    requirement: "700 ATP",
    maxGrind: 0,
    special: "Dark",
    atpMin: 650,
    atpMax: 650,
    ata: 55,
    ...KATANA_WEAPON_DEFAULTS,
    conditionalEffects: [
      {
        requirements: { armorLabels: ["Blue Odoshi Violet Nimaidou"] },
        bonuses: { ...ZERO_WEAPON_STAT_BONUSES, atp: 100, ata: 10 },
        weaponAtpMultiplierPercent: 0,
      },
    ],
    hex: '000800',
  },
  {
    id: 'guren',
    label: "Guren",
    requirement: "850 ATP",
    maxGrind: 0,
    special: "Burning",
    atpMin: 790,
    atpMax: 840,
    ata: 64,
    ...KATANA_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, mst: 5 },
    hex: '000800',
  },
  {
    id: 'shouren',
    label: "Shouren",
    requirement: "850 ATP",
    maxGrind: 0,
    special: "Blizzard",
    atpMin: 820,
    atpMax: 870,
    ata: 56,
    ...KATANA_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, mst: 5 },
    hex: '000800',
  },
  {
    id: 'agito_1975',
    label: "Agito (1975)",
    requirement: "500 ATP",
    maxGrind: 0,
    special: "Dim",
    atpMin: 460,
    atpMax: 480,
    ata: 45,
    ...KATANA_WEAPON_DEFAULTS,
    conditionalEffects: [
      {
        requirements: { armorLabels: ["Samurai Armor"] },
        bonuses: { ...ZERO_WEAPON_STAT_BONUSES, ata: 20 },
        weaponAtpMultiplierPercent: 0,
      },
    ],
    hex: '000800',
  },
  {
    id: 'yasha',
    label: "Yasha",
    requirement: "650 ATP",
    maxGrind: 0,
    special: "Fill",
    atpMin: 500,
    atpMax: 550,
    ata: 50,
    ...KATANA_WEAPON_DEFAULTS,
    conditionalEffects: [
      {
        requirements: { armorLabels: ["Blue Odoshi Violet Nimaidou"] },
        bonuses: { ...ZERO_WEAPON_STAT_BONUSES, atp: 100, ata: 10 },
        weaponAtpMultiplierPercent: 0,
      },
    ],
    hex: '000800',
  },
  {
    id: 'orotiagito',
    label: "Orotiagito",
    requirement: "850 ATP",
    maxGrind: 0,
    special: "See Notes",
    atpMin: 750,
    atpMax: 800,
    ata: 55,
    ...KATANA_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, mst: 15 },
    conditionalEffects: [
      {
        requirements: { armorLabels: ["Samurai Armor"] },
        bonuses: { ...ZERO_WEAPON_STAT_BONUSES, ata: 20 },
        weaponAtpMultiplierPercent: 30,
      },
    ],
    hex: '000800',
  },
  {
    id: 'typejs_j_sword',
    label: "TypeJS/J-Sword",
    requirement: "350 ATP",
    maxGrind: 125,
    special: "None",
    atpMin: 130,
    atpMax: 130,
    ata: 50,
    ...KATANA_WEAPON_DEFAULTS,
    hex: '000800',
  },
  {
    id: 'typejs_saber',
    label: "TypeJS/Saber",
    requirement: "350 ATP",
    maxGrind: 125,
    special: "None",
    atpMin: 100,
    atpMax: 140,
    ata: 40,
    ...KATANA_WEAPON_DEFAULTS,
    hex: '000800',
  },
  {
    id: 'typejs_slicer',
    label: "TypeJS/Slicer",
    requirement: "350 ATP",
    maxGrind: 125,
    special: "None",
    atpMin: 100,
    atpMax: 130,
    ata: 55,
    ...KATANA_WEAPON_DEFAULTS,
    hex: '000800',
  },
  {
    id: 'es_katana',
    label: "ES Katana",
    requirement: "800 ATP",
    maxGrind: 250,
    special: "Varies",
    atpMin: 170,
    atpMax: 170,
    ata: 50,
    ...KATANA_WEAPON_DEFAULTS,
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal'],
    hex: '000800',
  },
  {
    id: 'es_hammer',
    label: "ES Hammer",
    requirement: "800 ATP",
    maxGrind: 250,
    special: "Varies",
    atpMin: 150,
    atpMax: 150,
    ata: 50,
    ...KATANA_WEAPON_DEFAULTS,
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal', 'fomar', 'fomarl', 'fonewm'],
    hex: '000800',
  },
  {
    id: 'es_harisen',
    label: "ES Harisen",
    requirement: "800 ATP",
    maxGrind: 250,
    special: "Varies",
    atpMin: 150,
    atpMax: 150,
    ata: 50,
    ...KATANA_WEAPON_DEFAULTS,
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal', 'fomar', 'fomarl', 'fonewm'],
    hex: '000800',
  },
// --- TWIN_SWORDS ---
  {
    id: 'musashi',
    label: "Musashi",
    requirement: "385 ATP",
    maxGrind: 40,
    special: "Berserk",
    atpMin: 330,
    atpMax: 350,
    ata: 35,
    ...TWIN_SWORD_WEAPON_DEFAULTS,
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal'],
    hex: '000900',
  },
  {
    id: 'yamato',
    label: "Yamato",
    requirement: "470 ATP",
    maxGrind: 60,
    special: "Blizzard",
    atpMin: 380,
    atpMax: 390,
    ata: 40,
    ...TWIN_SWORD_WEAPON_DEFAULTS,
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal'],
    hex: '000900',
  },
  {
    id: 'g_assassins_sabers',
    label: "G-Assassin's Sabers",
    requirement: "390 ATP",
    maxGrind: 25,
    special: "Arrest",
    atpMin: 350,
    atpMax: 360,
    ata: 35,
    ...TWIN_SWORD_WEAPON_DEFAULTS,
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '000900',
  },
  {
    id: 'asuka',
    label: "Asuka",
    requirement: "650 ATP",
    maxGrind: 30,
    special: "Burning",
    atpMin: 560,
    atpMax: 570,
    ata: 50,
    ...TWIN_SWORD_WEAPON_DEFAULTS,
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal'],
    hex: '000900',
  },
  {
    id: 'sange_and_yasha',
    label: "Sange & Yasha",
    requirement: "800 ATP",
    maxGrind: 30,
    special: "Gush",
    atpMin: 640,
    atpMax: 650,
    ata: 50,
    ...TWIN_SWORD_WEAPON_DEFAULTS,
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal'],
    conditionalEffects: [
      {
        requirements: { armorLabels: ["Blue Odoshi Violet Nimaidou"] },
        bonuses: { ...ZERO_WEAPON_STAT_BONUSES, atp: 100, ata: 10 },
        weaponAtpMultiplierPercent: 0,
      },
    ],
    hex: '000900',
  },
  {
    id: 'jizai',
    label: "Jizai",
    requirement: "800 ATP",
    maxGrind: 40,
    special: "Hell",
    atpMin: 800,
    atpMax: 810,
    ata: 55,
    ...TWIN_SWORD_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, mst: 10 },
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal'],
    hex: '000900',
  },
  {
    id: 'typess_swords',
    label: "TypeSS/Swords",
    requirement: "350 ATP",
    maxGrind: 125,
    special: "None",
    atpMin: 150,
    atpMax: 150,
    ata: 45,
    ...TWIN_SWORD_WEAPON_DEFAULTS,
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal'],
    hex: '000900',
  },
  {
    id: 'es_swords',
    label: "ES Swords",
    requirement: "800 ATP",
    maxGrind: 250,
    special: "Varies",
    atpMin: 180,
    atpMax: 180,
    ata: 45,
    ...TWIN_SWORD_WEAPON_DEFAULTS,
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal'],
    hex: '000900',
  },
// --- FISTS ---
  {
    id: 'brave_knuckle',
    label: "Brave Knuckle",
    requirement: "400 ATP",
    maxGrind: 30,
    special: "Hold",
    atpMin: 380,
    atpMax: 460,
    ata: 60,
    ...FIST_WEAPON_DEFAULTS,
    hex: '000A00',
  },
  {
    id: 'sonic_knuckle',
    label: "Sonic Knuckle",
    requirement: "412 ATP",
    maxGrind: 0,
    special: "King's",
    atpMin: 260,
    atpMax: 310,
    ata: 75,
    ...FIST_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, dfp: 10, mst: 10, evp: 10, lck: 10 },
    hex: '000A00',
  },
  {
    id: 'star_song',
    label: "Star Song",
    requirement: "570 ATP",
    maxGrind: 50,
    special: "None",
    atpMin: 500,
    atpMax: 520,
    ata: 50,
    ...FIST_WEAPON_DEFAULTS,
    compatibleClasses: ['humar', 'hunewearl', 'ramar', 'ramarl', 'fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '000A00',
  },
  {
    id: 'angry_fist',
    label: "Angry Fist",
    requirement: "610 ATP",
    maxGrind: 50,
    special: "Freeze",
    atpMin: 460,
    atpMax: 560,
    ata: 62,
    ...FIST_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, dfp: 10 },
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal', 'fomar', 'fomarl', 'fonewm'],
    hex: '000A00',
  },
  {
    id: 'god_hand',
    label: "God Hand",
    requirement: "800 ATP",
    maxGrind: 30,
    special: "King's",
    atpMin: 585,
    atpMax: 705,
    ata: 75,
    ...FIST_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, dfp: 5, mst: 5, evp: 5, lck: 5 },
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '000A00',
  },
  {
    id: 'sacred_duster',
    label: "Sacred Duster",
    requirement: "800 ATP",
    maxGrind: 25,
    special: "Blizzard",
    atpMin: 660,
    atpMax: 730,
    ata: 67,
    ...FIST_WEAPON_DEFAULTS,
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '000A00',
  },
  {
    id: 'typekn_blade',
    label: "TypeKN/Blade",
    requirement: "350 ATP",
    maxGrind: 125,
    special: "None",
    atpMin: 180,
    atpMax: 200,
    ata: 70,
    ...FIST_WEAPON_DEFAULTS,
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal'],
    hex: '000A00',
  },
  {
    id: 'typekn_claw',
    label: "TypeKN/Claw",
    requirement: "350 ATP",
    maxGrind: 125,
    special: "None",
    atpMin: 120,
    atpMax: 220,
    ata: 65,
    ...FIST_WEAPON_DEFAULTS,
    hex: '000A00',
  },
  {
    id: 'es_knuckle',
    label: "ES Knuckle",
    requirement: "800 ATP",
    maxGrind: 250,
    special: "Varies",
    atpMin: 250,
    atpMax: 250,
    ata: 65,
    ...FIST_WEAPON_DEFAULTS,
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal', 'fomar', 'fomarl', 'fonewm'],
    hex: '000A00',
  },
// --- HANDGUNS ---
  {
    id: 'handgun',
    label: "Handgun",
    requirement: "68 ATA",
    maxGrind: 75,
    special: "None",
    atpMin: 20,
    atpMax: 30,
    ata: 26,
    ...HANDGUN_WEAPON_DEFAULTS,
    hex: '010100',
  },
  {
    id: 'autogun',
    label: "Autogun",
    requirement: "78 ATA",
    maxGrind: 50,
    special: "None",
    atpMin: 45,
    atpMax: 65,
    ata: 29,
    ...HANDGUN_WEAPON_DEFAULTS,
    hex: '010100',
  },
  {
    id: 'lockgun',
    label: "Lockgun",
    requirement: "88 ATA",
    maxGrind: 35,
    special: "None",
    atpMin: 80,
    atpMax: 100,
    ata: 31,
    ...HANDGUN_WEAPON_DEFAULTS,
    hex: '010100',
  },
  {
    id: 'railgun',
    label: "Railgun",
    requirement: "98 ATA",
    maxGrind: 25,
    special: "None",
    atpMin: 120,
    atpMax: 140,
    ata: 33,
    ...HANDGUN_WEAPON_DEFAULTS,
    hex: '010100',
  },
  {
    id: 'raygun',
    label: "Raygun",
    requirement: "108 ATA",
    maxGrind: 15,
    special: "None",
    atpMin: 150,
    atpMax: 180,
    ata: 35,
    ...HANDGUN_WEAPON_DEFAULTS,
    hex: '010100',
  },
  {
    id: 'tension_blaster',
    label: "Tension Blaster",
    requirement: "100 ATA",
    maxGrind: 0,
    special: "Seize",
    atpMin: 280,
    atpMax: 310,
    ata: 57,
    ...HANDGUN_WEAPON_DEFAULTS,
    hex: '010100',
  },
  {
    id: 'varista',
    label: "Varista",
    requirement: "110 ATA",
    maxGrind: 25,
    special: "Seize",
    atpMin: 155,
    atpMax: 210,
    ata: 38,
    ...HANDGUN_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, evp: 10 },
    hex: '010100',
  },
  {
    id: 'custom_ray_ver_oo',
    label: "Custom Ray ver.OO",
    requirement: "114 ATA",
    maxGrind: 20,
    special: "Flame",
    atpMin: 165,
    atpMax: 195,
    ata: 40,
    ...HANDGUN_WEAPON_DEFAULTS,
    hex: '010100',
  },
  {
    id: 'bravace',
    label: "Bravace",
    requirement: "118 ATA",
    maxGrind: 30,
    special: "Storm",
    atpMin: 190,
    atpMax: 230,
    ata: 40,
    ...HANDGUN_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, dfp: 15 },
    hex: '010100',
  },
  {
    id: 'suppressed_gun',
    label: "Suppressed Gun",
    requirement: "110 ATA",
    maxGrind: 9,
    special: "None",
    atpMin: 260,
    atpMax: 270,
    ata: 47,
    ...HANDGUN_WEAPON_DEFAULTS,
    hex: '010100',
  },
  {
    id: 'red_handgun',
    label: "Red Handgun",
    requirement: "140 ATA",
    maxGrind: 50,
    special: "Storm",
    atpMin: 300,
    atpMax: 300,
    ata: 46,
    ...HANDGUN_WEAPON_DEFAULTS,
    hex: '010100',
  },
  {
    id: 'ruby_bullet',
    label: "Ruby Bullet",
    requirement: "160 ATA",
    maxGrind: 0,
    special: "Burning",
    atpMin: 350,
    atpMax: 350,
    ata: 60,
    ...HANDGUN_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, dfp: 10 },
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010100',
  },
  {
    id: 'yasminkov_2000h',
    label: "Yasminkov 2000H",
    requirement: "164 ATA",
    maxGrind: 10,
    special: "None",
    atpMin: 340,
    atpMax: 340,
    ata: 45,
    ...HANDGUN_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    conditionalEffects: [
      {
        requirements: { shieldLabels: ["Gratia"] },
        bonuses: { ...ZERO_WEAPON_STAT_BONUSES, ata: 30 },
        weaponAtpMultiplierPercent: 0,
      },
    ],
    hex: '010100',
  },
  {
    id: 'handgun_guld',
    label: "Handgun: Guld",
    requirement: "167 ATA",
    maxGrind: 9,
    special: "Soul",
    atpMin: 370,
    atpMax: 400,
    ata: 38,
    ...HANDGUN_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'racast'],
    hex: '010100',
  },
  {
    id: 'handgun_milla',
    label: "Handgun: Milla",
    requirement: "168 ATA",
    maxGrind: 9,
    special: "Fill",
    atpMin: 350,
    atpMax: 360,
    ata: 48,
    ...HANDGUN_WEAPON_DEFAULTS,
    compatibleClasses: ['ramarl', 'racaseal'],
    hex: '010100',
  },
  {
    id: 'ophelie_seize',
    label: "Ophelie Seize",
    requirement: "170 ATA",
    maxGrind: 9,
    special: "Chaos",
    atpMin: 390,
    atpMax: 420,
    ata: 50,
    ...HANDGUN_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010100',
  },
  {
    id: 'master_raven',
    label: "Master Raven",
    requirement: "150 ATA",
    maxGrind: 9,
    special: "Master's",
    atpMin: 350,
    atpMax: 380,
    ata: 52,
    ...HANDGUN_WEAPON_DEFAULTS,
    compatibleClasses: ['humar', 'hucast', 'ramar', 'racast', 'fomar', 'fonewm'],
    hex: '010100',
  },
  {
    id: 'last_swan',
    label: "Last Swan",
    requirement: "150 ATA",
    maxGrind: 9,
    special: "Lord's",
    atpMin: 80,
    atpMax: 90,
    ata: 32,
    ...HANDGUN_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, mst: 5 },
    compatibleClasses: ['hunewearl', 'hucaseal', 'ramarl', 'racaseal', 'fomarl', 'fonewearl'],
    hex: '010100',
  },
  {
    id: 'heaven_striker',
    label: "Heaven Striker",
    requirement: "200 ATA",
    maxGrind: 20,
    special: "See Notes",
    atpMin: 550,
    atpMax: 660,
    ata: 55,
    ...HANDGUN_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    conditionalEffects: [
      {
        requirements: { magLabels: ["Striker Unit"] },
        bonuses: { ...ZERO_WEAPON_STAT_BONUSES },
        weaponAtpMultiplierPercent: 0,
      },
    ],
    hex: '010100',
  },
  {
    id: 'heaven_punisher',
    label: "Heaven Punisher",
    requirement: "210 ATA",
    maxGrind: 0,
    special: "See Notes",
    atpMin: 300,
    atpMax: 330,
    ata: 50,
    ...HANDGUN_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010100',
  },
  {
    id: 'typegu_hand',
    label: "TypeGU/Hand",
    requirement: "90 ATA",
    maxGrind: 95,
    special: "None",
    atpMin: 10,
    atpMax: 10,
    ata: 45,
    ...HANDGUN_WEAPON_DEFAULTS,
    hex: '010100',
  },
  {
    id: 'typegu_mechgun',
    label: "TypeGU/Mechgun",
    requirement: "90 ATA",
    maxGrind: 90,
    special: "None",
    atpMin: 10,
    atpMax: 10,
    ata: 50,
    ...HANDGUN_WEAPON_DEFAULTS,
    hex: '010100',
  },
  {
    id: 'es_gun',
    label: "ES Gun",
    requirement: "180 ATA",
    maxGrind: 200,
    special: "Varies",
    atpMin: 10,
    atpMax: 10,
    ata: 45,
    ...HANDGUN_WEAPON_DEFAULTS,
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal', 'fonewm', 'fonewearl'],
    hex: '010100',
  },
// --- RIFLES ---
  {
    id: 'rifle',
    label: "Rifle",
    requirement: "72 ATA",
    maxGrind: 65,
    special: "None",
    atpMin: 10,
    atpMax: 50,
    ata: 38,
    ...RIFLE_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010200',
  },
  {
    id: 'sniper',
    label: "Sniper",
    requirement: "83 ATA",
    maxGrind: 55,
    special: "None",
    atpMin: 50,
    atpMax: 90,
    ata: 41,
    ...RIFLE_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010200',
  },
  {
    id: 'blaster',
    label: "Blaster",
    requirement: "100 ATA",
    maxGrind: 45,
    special: "None",
    atpMin: 100,
    atpMax: 130,
    ata: 44,
    ...RIFLE_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010200',
  },
  {
    id: 'beam',
    label: "Beam",
    requirement: "106 ATA",
    maxGrind: 35,
    special: "None",
    atpMin: 140,
    atpMax: 170,
    ata: 47,
    ...RIFLE_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010200',
  },
  {
    id: 'laser',
    label: "Laser",
    requirement: "115 ATA",
    maxGrind: 25,
    special: "None",
    atpMin: 200,
    atpMax: 210,
    ata: 50,
    ...RIFLE_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010200',
  },
  {
    id: 'drill_launcher',
    label: "Drill Launcher",
    requirement: "100 ATA",
    maxGrind: 0,
    special: "Pierce",
    atpMin: 180,
    atpMax: 200,
    ata: 50,
    ...RIFLE_WEAPON_DEFAULTS,
    compatibleClasses: ['hucast', 'hucaseal', 'racast', 'racaseal'],
    hex: '010200',
  },
  {
    id: 'visk_235w',
    label: "Visk-235W",
    requirement: "118 ATA",
    maxGrind: 15,
    special: "Seize",
    atpMin: 220,
    atpMax: 250,
    ata: 53,
    ...RIFLE_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, evp: 5 },
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010200',
  },
  {
    id: 'wals_mk2',
    label: "Wals-MK2",
    requirement: "120 ATA",
    maxGrind: 9,
    special: "Havoc",
    atpMin: 260,
    atpMax: 280,
    ata: 56,
    ...RIFLE_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010200',
  },
  {
    id: 'justy_23st',
    label: "Justy-23ST",
    requirement: "125 ATA",
    maxGrind: 15,
    special: "Devil's",
    atpMin: 290,
    atpMax: 320,
    ata: 58,
    ...RIFLE_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010200',
  },
  {
    id: 'le_cogneur',
    label: "Le Cogneur",
    requirement: "140 ATA",
    maxGrind: 0,
    special: "None",
    atpMin: 310,
    atpMax: 330,
    ata: 60,
    ...RIFLE_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010200',
  },
  {
    id: 'rianov_303snr',
    label: "Rianov 303SNR",
    requirement: "144 ATA",
    maxGrind: 60,
    special: "None",
    atpMin: 300,
    atpMax: 300,
    ata: 60,
    ...RIFLE_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    conditionalEffects: [
      {
        requirements: { shieldLabels: ["Gratia"] },
        bonuses: { ...ZERO_WEAPON_STAT_BONUSES, dfp: -10, ata: -20 },
        weaponAtpMultiplierPercent: 0,
      },
    ],
    hex: '010200',
  },
  {
    id: 'tanegashima',
    label: "Tanegashima",
    requirement: "190 ATA",
    maxGrind: 0,
    special: "None",
    atpMin: 320,
    atpMax: 410,
    ata: 38,
    ...RIFLE_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010200',
  },
  {
    id: 'spread_needle',
    label: "Spread Needle",
    requirement: "135 ATA",
    maxGrind: 40,
    special: "Seize",
    atpMin: 1,
    atpMax: 110,
    ata: 40,
    ...RIFLE_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, evp: -30 },
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010200',
  },
  {
    id: 'bringers_rifle',
    label: "Bringer's Rifle",
    requirement: "140 ATA",
    maxGrind: 9,
    special: "Demon's",
    atpMin: 330,
    atpMax: 370,
    ata: 63,
    ...RIFLE_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, evp: -20 },
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal', 'fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '010200',
  },
  {
    id: 'egg_blaster',
    label: "Egg Blaster",
    requirement: "140 ATA",
    maxGrind: 0,
    special: "Flame",
    atpMin: 300,
    atpMax: 330,
    ata: 40,
    ...RIFLE_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010200',
  },
  {
    id: 'rianov_303snr_1',
    label: "Rianov 303SNR-1",
    requirement: "144 ATA",
    maxGrind: 50,
    special: "None",
    atpMin: 350,
    atpMax: 400,
    ata: 50,
    ...RIFLE_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    conditionalEffects: [
      {
        requirements: { shieldLabels: ["Gratia"] },
        bonuses: { ...ZERO_WEAPON_STAT_BONUSES, dfp: -10, ata: -20 },
        weaponAtpMultiplierPercent: 0,
      },
    ],
    hex: '010200',
  },
  {
    id: 'rianov_303snr_2',
    label: "Rianov 303SNR-2",
    requirement: "144 ATA",
    maxGrind: 25,
    special: "None",
    atpMin: 150,
    atpMax: 400,
    ata: 30,
    ...RIFLE_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    conditionalEffects: [
      {
        requirements: { shieldLabels: ["Gratia"] },
        bonuses: { ...ZERO_WEAPON_STAT_BONUSES, dfp: -10, ata: -20 },
        weaponAtpMultiplierPercent: 0,
      },
    ],
    hex: '010200',
  },
  {
    id: 'rianov_303snr_3',
    label: "Rianov 303SNR-3",
    requirement: "194 ATA",
    maxGrind: 15,
    special: "None",
    atpMin: 500,
    atpMax: 500,
    ata: 65,
    ...RIFLE_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, mst: 50 },
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    conditionalEffects: [
      {
        requirements: { shieldLabels: ["Gratia"] },
        bonuses: { ...ZERO_WEAPON_STAT_BONUSES, dfp: -10, ata: -20 },
        weaponAtpMultiplierPercent: 0,
      },
    ],
    hex: '010200',
  },
  {
    id: 'rianov_303snr_4',
    label: "Rianov 303SNR-4",
    requirement: "194 ATA",
    maxGrind: 60,
    special: "None",
    atpMin: 350,
    atpMax: 450,
    ata: 60,
    ...RIFLE_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    conditionalEffects: [
      {
        requirements: { shieldLabels: ["Gratia"] },
        bonuses: { ...ZERO_WEAPON_STAT_BONUSES, dfp: -10, ata: -20 },
        weaponAtpMultiplierPercent: 0,
      },
    ],
    hex: '010200',
  },
  {
    id: 'frozen_shooter',
    label: "Frozen Shooter",
    requirement: "162 ATA",
    maxGrind: 9,
    special: "See Notes",
    atpMin: 240,
    atpMax: 250,
    ata: 60,
    ...RIFLE_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010200',
  },
  {
    id: 'anti_android_rifle',
    label: "Anti Android Rifle",
    requirement: "163 ATA",
    maxGrind: 9,
    special: "Tempest",
    atpMin: 330,
    atpMax: 350,
    ata: 60,
    ...RIFLE_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010200',
  },
  {
    id: 'yasminkov_3000r',
    label: "Yasminkov 3000R",
    requirement: "171 ATA",
    maxGrind: 60,
    special: "None",
    atpMin: 370,
    atpMax: 400,
    ata: 66,
    ...RIFLE_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    conditionalEffects: [
      {
        requirements: { shieldLabels: ["Gratia"] },
        bonuses: { ...ZERO_WEAPON_STAT_BONUSES, ata: 30 },
        weaponAtpMultiplierPercent: 0,
      },
    ],
    hex: '010200',
  },
  {
    id: 'ano_rifle',
    label: "Ano Rifle",
    requirement: "174 ATA",
    maxGrind: 15,
    special: "Seize",
    atpMin: 350,
    atpMax: 380,
    ata: 64,
    ...RIFLE_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010200',
  },
  {
    id: 'yasminkov_7000v',
    label: "Yasminkov 7000V",
    requirement: "190 ATA",
    maxGrind: 25,
    special: "None",
    atpMin: 370,
    atpMax: 450,
    ata: 67,
    ...RIFLE_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    conditionalEffects: [
      {
        requirements: { shieldLabels: ["Gratia"] },
        bonuses: { ...ZERO_WEAPON_STAT_BONUSES, ata: 30 },
        weaponAtpMultiplierPercent: 0,
      },
    ],
    hex: '010200',
  },
  {
    id: 'holy_ray',
    label: "Holy Ray",
    requirement: "680 MST",
    maxGrind: 40,
    special: "Arrest",
    atpMin: 290,
    atpMax: 300,
    ata: 70,
    ...RIFLE_WEAPON_DEFAULTS,
    compatibleClasses: ['humar', 'hunewearl', 'ramarl', 'fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '010200',
  },
  {
    id: 'angel_harp',
    label: "Angel Harp",
    requirement: "120 ATA",
    maxGrind: 0,
    special: "Chaos",
    atpMin: 300,
    atpMax: 320,
    ata: 60,
    ...RIFLE_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, dfp: 10 },
    compatibleClasses: ['ramarl', 'racaseal', 'fomarl', 'fonewearl'],
    conditionalEffects: [
      {
        requirements: { armorLabels: ["Sweetheart"] },
        bonuses: { ...ZERO_WEAPON_STAT_BONUSES, ata: 12 },
        weaponAtpMultiplierPercent: 30,
      },
    ],
    hex: '010200',
  },
  {
    id: 'snow_queen',
    label: "Snow Queen",
    requirement: "162 ATA",
    maxGrind: 18,
    special: "See Notes",
    atpMin: 330,
    atpMax: 350,
    ata: 60,
    ...RIFLE_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010200',
  },
  {
    id: 'rianov_303snr_5',
    label: "Rianov 303SNR-5",
    requirement: "194 ATA",
    maxGrind: 0,
    special: "Dark",
    atpMin: 550,
    atpMax: 550,
    ata: 70,
    ...RIFLE_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, mst: 30 },
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    conditionalEffects: [
      {
        requirements: { shieldLabels: ["Gratia"] },
        bonuses: { ...ZERO_WEAPON_STAT_BONUSES, dfp: -10, ata: -20 },
        weaponAtpMultiplierPercent: 0,
      },
    ],
    hex: '010200',
  },
  {
    id: 'typeri_rifle',
    label: "TypeRI/Rifle",
    requirement: "90 ATA",
    maxGrind: 100,
    special: "None",
    atpMin: 10,
    atpMax: 10,
    ata: 60,
    ...RIFLE_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010200',
  },
  {
    id: 'es_rifle',
    label: "ES Rifle",
    requirement: "180 ATA",
    maxGrind: 220,
    special: "Varies",
    atpMin: 10,
    atpMax: 10,
    ata: 60,
    ...RIFLE_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010200',
  },
  {
    id: 'es_needle',
    label: "ES Needle",
    requirement: "180 ATA",
    maxGrind: 70,
    special: "Varies",
    atpMin: 10,
    atpMax: 10,
    ata: 40,
    ...RIFLE_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, evp: -30 },
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010200',
  },
// --- MECHGUNS ---
  {
    id: 'mechgun',
    label: "Mechgun",
    requirement: "79 ATA",
    maxGrind: 9,
    special: "None",
    atpMin: 2,
    atpMax: 4,
    ata: 0,
    ...MECHGUN_WEAPON_DEFAULTS,
    hex: '010300',
  },
  {
    id: 'assault',
    label: "Assault",
    requirement: "87 ATA",
    maxGrind: 9,
    special: "None",
    atpMin: 5,
    atpMax: 8,
    ata: 3,
    ...MECHGUN_WEAPON_DEFAULTS,
    hex: '010300',
  },
  {
    id: 'repeater',
    label: "Repeater",
    requirement: "97 ATA",
    maxGrind: 9,
    special: "None",
    atpMin: 5,
    atpMax: 12,
    ata: 6,
    ...MECHGUN_WEAPON_DEFAULTS,
    hex: '010300',
  },
  {
    id: 'gatling',
    label: "Gatling",
    requirement: "109 ATA",
    maxGrind: 9,
    special: "None",
    atpMin: 5,
    atpMax: 16,
    ata: 9,
    ...MECHGUN_WEAPON_DEFAULTS,
    hex: '010300',
  },
  {
    id: 'vulcan',
    label: "Vulcan",
    requirement: "117 ATA",
    maxGrind: 9,
    special: "None",
    atpMin: 5,
    atpMax: 20,
    ata: 12,
    ...MECHGUN_WEAPON_DEFAULTS,
    hex: '010300',
  },
  {
    id: 'samba_maracas',
    label: "Samba Maracas",
    requirement: "100 ATA",
    maxGrind: 0,
    special: "Havoc",
    atpMin: 5,
    atpMax: 10,
    ata: 10,
    ...MECHGUN_WEAPON_DEFAULTS,
    hex: '010300',
  },
  {
    id: 'rocket_punch',
    label: "Rocket Punch",
    requirement: "100 ATA",
    maxGrind: 50,
    special: "Burning",
    atpMin: 50,
    atpMax: 300,
    ata: 10,
    ...MECHGUN_WEAPON_DEFAULTS,
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010300',
  },
  {
    id: 'm_and_a60_vise',
    label: "M&A60 Vise",
    requirement: "120 ATA",
    maxGrind: 9,
    special: "Berserk",
    atpMin: 15,
    atpMax: 25,
    ata: 15,
    ...MECHGUN_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, lck: 5 },
    hex: '010300',
  },
  {
    id: 'h_and_s25_justice',
    label: "H&S25 Justice",
    requirement: "122 ATA",
    maxGrind: 9,
    special: 'Freeze (Reduced)',
    atpMin: 15,
    atpMax: 30,
    ata: 18,
    ...MECHGUN_WEAPON_DEFAULTS,
    hex: '010300',
  },
  {
    id: 'l_and_k14_combat',
    label: "L&K14 Combat",
    requirement: "124 ATA",
    maxGrind: 20,
    special: 'Seize (Reduced)',
    atpMin: 15,
    atpMax: 30,
    ata: 18,
    ...MECHGUN_WEAPON_DEFAULTS,
    hex: '010300',
  },
  {
    id: 'twin_psychogun',
    label: "Twin Psychogun",
    requirement: "100 ATA",
    maxGrind: 0,
    special: "See Notes",
    atpMin: 35,
    atpMax: 40,
    ata: 23,
    ...MECHGUN_WEAPON_DEFAULTS,
    compatibleClasses: ['humar', 'hunewearl', 'ramar', 'ramarl'],
    hex: '010300',
  },
  {
    id: 'red_mechgun',
    label: "Red Mechgun",
    requirement: "155 ATA",
    maxGrind: 30,
    special: "Havoc",
    atpMin: 50,
    atpMax: 50,
    ata: 25,
    ...MECHGUN_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010300',
  },
  {
    id: 'yasminkov_9000m',
    label: "Yasminkov 9000M",
    requirement: "168 ATA",
    maxGrind: 10,
    special: "None",
    atpMin: 40,
    atpMax: 80,
    ata: 27,
    ...MECHGUN_WEAPON_DEFAULTS,
    conditionalEffects: [
      {
        requirements: { shieldLabels: ["Gratia"] },
        bonuses: { ...ZERO_WEAPON_STAT_BONUSES, ata: 30 },
        weaponAtpMultiplierPercent: 0,
      },
    ],
    hex: '010300',
  },
  {
    id: 'rage_de_foudre',
    label: "Rage de Foudre",
    requirement: "190 ATA",
    maxGrind: 9,
    special: "Tempest",
    atpMin: 175,
    atpMax: 185,
    ata: 40,
    ...MECHGUN_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010300',
  },
  {
    id: 'rage_de_glace',
    label: "Rage de Glace",
    requirement: "190 ATA",
    maxGrind: 9,
    special: "Blizzard",
    atpMin: 175,
    atpMax: 185,
    ata: 40,
    ...MECHGUN_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010300',
  },
  {
    id: 'rage_dame',
    label: "Rage d'Ame",
    requirement: "190 ATA",
    maxGrind: 9,
    special: "Geist",
    atpMin: 175,
    atpMax: 185,
    ata: 40,
    ...MECHGUN_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010300',
  },
  {
    id: 'rage_de_feu',
    label: "Rage de Feu",
    requirement: "190 ATA",
    maxGrind: 9,
    special: "Burning",
    atpMin: 175,
    atpMax: 185,
    ata: 40,
    ...MECHGUN_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010300',
  },
  {
    id: 'guld_milla',
    label: "Guld Milla",
    requirement: "190 ATA",
    maxGrind: 9,
    special: "Gush",
    atpMin: 180,
    atpMax: 200,
    ata: 30,
    ...MECHGUN_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010300',
  },
  {
    id: 'mille_marteaux',
    label: "Mille Marteaux",
    requirement: "190 ATA",
    maxGrind: 12,
    special: "See Notes",
    atpMin: 200,
    atpMax: 220,
    ata: 45,
    ...MECHGUN_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, mst: 10 },
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010300',
  },
  {
    id: 'dual_bird',
    label: "Dual Bird",
    requirement: "210 ATA",
    maxGrind: 21,
    special: "King's",
    atpMin: 200,
    atpMax: 210,
    ata: 22,
    ...MECHGUN_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, mst: 10 },
    compatibleClasses: ['hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010300',
  },
  {
    id: 'typeme_mechgun',
    label: "TypeME/Mechgun",
    requirement: "90 ATA",
    maxGrind: 30,
    special: "None",
    atpMin: 10,
    atpMax: 10,
    ata: 20,
    ...MECHGUN_WEAPON_DEFAULTS,
    hex: '010300',
  },
  {
    id: 'es_mechgun',
    label: "ES Mechgun",
    requirement: "180 ATA",
    maxGrind: 50,
    special: "Varies",
    atpMin: 10,
    atpMax: 10,
    ata: 20,
    ...MECHGUN_WEAPON_DEFAULTS,
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal', 'fonewm', 'fonewearl'],
    hex: '010300',
  },
  {
    id: 'es_psychogun',
    label: "ES Psychogun",
    requirement: "180 ATA",
    maxGrind: 50,
    special: "Varies",
    atpMin: 10,
    atpMax: 10,
    ata: 20,
    ...MECHGUN_WEAPON_DEFAULTS,
    hex: '010300',
  },
  {
    id: 'es_punch',
    label: "ES Punch",
    requirement: "180 ATA",
    maxGrind: 250,
    special: "Varies",
    atpMin: 10,
    atpMax: 10,
    ata: 40,
    ...MECHGUN_WEAPON_DEFAULTS,
    hex: '010300',
  },
// --- SHOTS ---
  {
    id: 'shot',
    label: "Shot",
    requirement: "85 ATA",
    maxGrind: 20,
    special: "None",
    atpMin: 20,
    atpMax: 25,
    ata: 27,
    ...SHOT_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, evp: -10 },
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010400',
  },
  {
    id: 'spread',
    label: "Spread",
    requirement: "90 ATA",
    maxGrind: 20,
    special: "None",
    atpMin: 30,
    atpMax: 50,
    ata: 28,
    ...SHOT_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, evp: -10 },
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010400',
  },
  {
    id: 'cannon',
    label: "Cannon",
    requirement: "102 ATA",
    maxGrind: 15,
    special: "None",
    atpMin: 40,
    atpMax: 80,
    ata: 30,
    ...SHOT_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, evp: -20 },
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010400',
  },
  {
    id: 'launcher',
    label: "Launcher",
    requirement: "112 ATA",
    maxGrind: 15,
    special: "None",
    atpMin: 50,
    atpMax: 110,
    ata: 31,
    ...SHOT_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, evp: -20 },
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010400',
  },
  {
    id: 'arms',
    label: "Arms",
    requirement: "120 ATA",
    maxGrind: 10,
    special: "None",
    atpMin: 60,
    atpMax: 140,
    ata: 33,
    ...SHOT_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, evp: -20 },
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010400',
  },
  {
    id: 'crush_bullet',
    label: "Crush Bullet",
    requirement: "122 ATA",
    maxGrind: 25,
    special: "Fill (Note",
    atpMin: 85,
    atpMax: 133,
    ata: 34,
    ...SHOT_WEAPON_DEFAULTS,
    hex: '010400',
  },
  {
    id: 'meteor_smash',
    label: "Meteor Smash",
    requirement: "125 ATA",
    maxGrind: 25,
    special: "Soul (Note",
    atpMin: 80,
    atpMax: 160,
    ata: 36,
    ...SHOT_WEAPON_DEFAULTS,
    hex: '010400',
  },
  {
    id: 'final_impact',
    label: "Final Impact",
    requirement: "125 ATA",
    maxGrind: 30,
    special: "Lord's (Note",
    atpMin: 95,
    atpMax: 170,
    ata: 36,
    ...SHOT_WEAPON_DEFAULTS,
    hex: '010400',
  },
  {
    id: 'inferno_bazooka',
    label: "Inferno Bazooka",
    requirement: "142 ATA",
    maxGrind: 9,
    special: "Devil's",
    atpMin: 230,
    atpMax: 410,
    ata: 41,
    ...SHOT_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, evp: -20 },
    hex: '010400',
  },
  {
    id: 'l_and_k38_combat',
    label: "L&K38 Combat",
    requirement: "145 ATA",
    maxGrind: 25,
    special: "Burning",
    atpMin: 150,
    atpMax: 250,
    ata: 40,
    ...SHOT_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, evp: -30 },
    hex: '010400',
  },
  {
    id: 'maser_beam',
    label: "Maser Beam",
    requirement: "160 ATA",
    maxGrind: 20,
    special: "None",
    atpMin: 230,
    atpMax: 230,
    ata: 37,
    ...SHOT_WEAPON_DEFAULTS,
    hex: '010400',
  },
  {
    id: 'flame_visit',
    label: "Flame Visit",
    requirement: "164 ATA",
    maxGrind: 9,
    special: "Havoc",
    atpMin: 300,
    atpMax: 450,
    ata: 40,
    ...SHOT_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010400',
  },
  {
    id: 'rambling_may',
    label: "Rambling May",
    requirement: "170 ATA",
    maxGrind: 0,
    special: "Chaos",
    atpMin: 360,
    atpMax: 450,
    ata: 45,
    ...SHOT_WEAPON_DEFAULTS,
    hex: '010400',
  },
  {
    id: 'panzer_faust',
    label: "Panzer Faust",
    requirement: "181 ATA",
    maxGrind: 9,
    special: "Chaos",
    atpMin: 350,
    atpMax: 500,
    ata: 42,
    ...SHOT_WEAPON_DEFAULTS,
    compatibleClasses: ['racast', 'racaseal'],
    hex: '010400',
  },
  {
    id: 'iron_faust',
    label: "Iron Faust",
    requirement: "181 ATA",
    maxGrind: 18,
    special: "Chaos",
    atpMin: 500,
    atpMax: 580,
    ata: 42,
    ...SHOT_WEAPON_DEFAULTS,
    compatibleClasses: ['racast', 'racaseal'],
    hex: '010400',
  },
  {
    id: 'baranz_launcher',
    label: "Baranz Launcher",
    requirement: "181 ATA",
    maxGrind: 30,
    special: "Charge",
    atpMin: 230,
    atpMax: 240,
    ata: 40,
    ...SHOT_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010400',
  },
  {
    id: 'belra_cannon',
    label: "Belra Cannon",
    requirement: "187 ATA",
    maxGrind: 20,
    special: "See Notes",
    atpMin: 400,
    atpMax: 500,
    ata: 45,
    ...SHOT_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010400',
  },
  {
    id: 'burning_visit',
    label: "Burning Visit",
    requirement: "164 ATA",
    maxGrind: 18,
    special: "Havoc",
    atpMin: 340,
    atpMax: 540,
    ata: 40,
    ...SHOT_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010400',
  },
  {
    id: 'power_maser',
    label: "Power Maser",
    requirement: "160 ATA",
    maxGrind: 20,
    special: "None",
    atpMin: 270,
    atpMax: 270,
    ata: 37,
    ...SHOT_WEAPON_DEFAULTS,
    hex: '010400',
  },
  {
    id: 'dark_meteor',
    label: "Dark Meteor",
    requirement: "190 ATA",
    maxGrind: 25,
    special: "See Notes",
    atpMin: 150,
    atpMax: 280,
    ata: 45,
    ...SHOT_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010400',
  },
  {
    id: 'typesh_shot',
    label: "TypeSH/Shot",
    requirement: "90 ATA",
    maxGrind: 60,
    special: "None",
    atpMin: 10,
    atpMax: 10,
    ata: 40,
    ...SHOT_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010400',
  },
  {
    id: 'es_shot',
    label: "ES Shot",
    requirement: "180 ATA",
    maxGrind: 125,
    special: "Varies",
    atpMin: 10,
    atpMax: 10,
    ata: 40,
    ...SHOT_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010400',
  },
  {
    id: 'es_bazooka',
    label: "ES Bazooka",
    requirement: "180 ATA",
    maxGrind: 250,
    special: "Varies",
    atpMin: 10,
    atpMax: 10,
    ata: 40,
    ...SHOT_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010400',
  },
// --- LAUNCHERS ---
  {
    id: 'photon_launcher',
    label: "Photon Launcher",
    requirement: "118 ATA",
    maxGrind: 9,
    special: "Hold",
    atpMin: 210,
    atpMax: 220,
    ata: 35,
    ...LAUNCHER_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, evp: 5 },
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010500',
  },
  {
    id: 'guilty_light',
    label: "Guilty Light",
    requirement: "120 ATA",
    maxGrind: 18,
    special: "Blizzard",
    atpMin: 240,
    atpMax: 250,
    ata: 38,
    ...LAUNCHER_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010500',
  },
  {
    id: 'red_scorpio',
    label: "Red Scorpio",
    requirement: "150 ATA",
    maxGrind: 50,
    special: "Burning",
    atpMin: 280,
    atpMax: 300,
    ata: 42,
    ...LAUNCHER_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010500',
  },
  {
    id: 'phonon_maser',
    label: "Phonon Maser",
    requirement: "155 ATA",
    maxGrind: 36,
    special: "Havoc",
    atpMin: 350,
    atpMax: 360,
    ata: 45,
    ...LAUNCHER_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010500',
  },
  {
    id: 'es_launcher',
    label: "ES Launcher",
    requirement: "180 ATA",
    maxGrind: 180,
    special: "Varies",
    atpMin: 10,
    atpMax: 10,
    ata: 40,
    ...LAUNCHER_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, evp: 5 },
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '010500',
  },
  {
    id: 'meteor_rouge',
    label: "Meteor Rouge",
    requirement: "140 ATA",
    maxGrind: 0,
    special: "Demon's",
    atpMin: 265,
    atpMax: 315,
    ata: 48,
    ...LAUNCHER_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hardDistance: 170,
    hardAngle: 26,
    veryHardDistance: 30,
    veryHardAngle: 26,
    hex: '010500',
  },
  {
    id: 'ano_bazooka',
    label: "Ano Bazooka",
    requirement: "170 ATA",
    maxGrind: 15,
    special: "None",
    atpMin: 350,
    atpMax: 370,
    ata: 30,
    ...LAUNCHER_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hardDistance: 170,
    hardAngle: 26,
    veryHardDistance: 30,
    veryHardAngle: 26,
    hex: '010500',
  },
  {
    id: 'gi_gue_bazooka',
    label: "Gi Gue Bazooka",
    requirement: "200 ATA",
    maxGrind: 0,
    special: "Seize",
    atpMin: 520,
    atpMax: 620,
    ata: 40,
    ...LAUNCHER_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hardDistance: 170,
    hardAngle: 26,
    veryHardDistance: 30,
    veryHardAngle: 26,
    hex: '010500',
  },
  {
    id: 'cannon_rouge',
    label: "Cannon Rouge",
    requirement: "200 ATA",
    maxGrind: 30,
    special: "Chaos",
    atpMin: 600,
    atpMax: 750,
    ata: 45,
    ...LAUNCHER_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hardDistance: 170,
    hardAngle: 26,
    veryHardDistance: 30,
    veryHardAngle: 26,
    hex: '010500',
  },
  {
    id: 'nug2000_bazooka',
    label: "NUG2000-Bazooka",
    requirement: "200 ATA",
    maxGrind: 32,
    special: "None",
    atpMin: 400,
    atpMax: 660,
    ata: 30,
    ...LAUNCHER_WEAPON_DEFAULTS,
    compatibleClasses: ['ramar', 'ramarl', 'racast', 'racaseal'],
    hardDistance: 170,
    hardAngle: 26,
    veryHardDistance: 30,
    veryHardAngle: 26,
    hex: '010500',
  },
// --- CANES ---
  {
    id: 'cane',
    label: "Cane",
    requirement: "50 MST",
    maxGrind: 55,
    special: "None",
    atpMin: 25,
    atpMax: 30,
    ata: 30,
    ...CANE_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, evp: 5 },
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020100',
  },
  {
    id: 'stick',
    label: "Stick",
    requirement: "150 MST",
    maxGrind: 40,
    special: "None",
    atpMin: 50,
    atpMax: 60,
    ata: 32,
    ...CANE_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, evp: 10 },
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020100',
  },
  {
    id: 'mace',
    label: "Mace",
    requirement: "300 MST",
    maxGrind: 25,
    special: "None",
    atpMin: 90,
    atpMax: 90,
    ata: 33,
    ...CANE_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, evp: 15 },
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020100',
  },
  {
    id: 'club',
    label: "Club",
    requirement: "420 MST",
    maxGrind: 10,
    special: "None",
    atpMin: 110,
    atpMax: 120,
    ata: 35,
    ...CANE_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, evp: 20 },
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020100',
  },
  {
    id: 'lollipop',
    label: "Lollipop",
    requirement: "222 ATP",
    maxGrind: 12,
    special: "Heart",
    atpMin: 150,
    atpMax: 200,
    ata: 32,
    ...CANE_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, mst: 33 },
    hex: '020100',
  },
  {
    id: 'flower_cane',
    label: "Flower Cane",
    requirement: "348 MST",
    maxGrind: 0,
    special: "None",
    atpMin: 168,
    atpMax: 180,
    ata: 41,
    ...CANE_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, mst: 50 },
    compatibleClasses: ['humar', 'hunewearl', 'ramar', 'ramarl', 'fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020100',
  },
  {
    id: 'club_of_laconium',
    label: "Club of Laconium",
    requirement: "430 MST",
    maxGrind: 9,
    special: "Flame",
    atpMin: 140,
    atpMax: 150,
    ata: 36,
    ...CANE_WEAPON_DEFAULTS,
    hex: '020100',
  },
  {
    id: 'mace_of_adaman',
    label: "Mace of Adaman",
    requirement: "440 MST",
    maxGrind: 9,
    special: "Freeze",
    atpMin: 170,
    atpMax: 170,
    ata: 38,
    ...CANE_WEAPON_DEFAULTS,
    hex: '020100',
  },
  {
    id: 'club_of_zumiuran',
    label: "Club of Zumiuran",
    requirement: "450 MST",
    maxGrind: 9,
    special: "Storm",
    atpMin: 178,
    atpMax: 180,
    ata: 39,
    ...CANE_WEAPON_DEFAULTS,
    hex: '020100',
  },
  {
    id: 'windmill',
    label: "Windmill",
    requirement: "690 MST",
    maxGrind: 9,
    special: "None",
    atpMin: 300,
    atpMax: 310,
    ata: 44,
    ...CANE_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, mst: 35 },
    compatibleClasses: ['humar', 'hunewearl', 'ramarl', 'fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020100',
  },
  {
    id: 'clio',
    label: "Clio",
    requirement: "900 MST",
    maxGrind: 0,
    special: "None",
    atpMin: 660,
    atpMax: 690,
    ata: 48,
    ...CANE_WEAPON_DEFAULTS,
    hex: '020100',
  },
  {
    id: 'summit_moon',
    label: "Summit Moon",
    requirement: "650 MST",
    maxGrind: 9,
    special: "Tempest",
    atpMin: 270,
    atpMax: 280,
    ata: 42,
    ...CANE_WEAPON_DEFAULTS,
    hex: '020100',
  },
  {
    id: 'decalog',
    label: "Decalog",
    requirement: "700 MST",
    maxGrind: 0,
    special: "Shifta",
    atpMin: 150,
    atpMax: 200,
    ata: 45,
    ...CANE_WEAPON_DEFAULTS,
    hex: '020100',
  },
  {
    id: 'es_cane',
    label: "ES Cane",
    requirement: "800 MST",
    maxGrind: 120,
    special: "Varies",
    atpMin: 10,
    atpMax: 10,
    ata: 40,
    ...CANE_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, evp: 5 },
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020100',
  },
  {
    id: 'es_moon',
    label: "ES Moon",
    requirement: "800 MST",
    maxGrind: 120,
    special: "Varies",
    atpMin: 10,
    atpMax: 10,
    ata: 40,
    ...CANE_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, mst: 35 },
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020100',
  },
  {
    id: 'es_windmill',
    label: "ES Windmill",
    requirement: "800 MST",
    maxGrind: 120,
    special: "Varies",
    atpMin: 10,
    atpMax: 10,
    ata: 40,
    ...CANE_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, mst: 35 },
    compatibleClasses: ['hunewearl', 'ramarl', 'fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020100',
  },
// --- RODS ---
  {
    id: 'rod',
    label: "Rod",
    requirement: "80 MST",
    maxGrind: 75,
    special: "None",
    atpMin: 25,
    atpMax: 45,
    ata: 35,
    ...ROD_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, dfp: 5 },
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020200',
  },
  {
    id: 'pole',
    label: "Pole",
    requirement: "200 MST",
    maxGrind: 50,
    special: "None",
    atpMin: 55,
    atpMax: 80,
    ata: 37,
    ...ROD_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, dfp: 10 },
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020200',
  },
  {
    id: 'pillar',
    label: "Pillar",
    requirement: "340 MST",
    maxGrind: 30,
    special: "None",
    atpMin: 85,
    atpMax: 155,
    ata: 38,
    ...ROD_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, dfp: 15 },
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020200',
  },
  {
    id: 'striker',
    label: "Striker",
    requirement: "450 MST",
    maxGrind: 20,
    special: "None",
    atpMin: 100,
    atpMax: 150,
    ata: 39,
    ...ROD_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, dfp: 20 },
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020200',
  },
  {
    id: 'broom',
    label: "Broom",
    requirement: "348 MST",
    maxGrind: 0,
    special: "Havoc",
    atpMin: 90,
    atpMax: 230,
    ata: 35,
    ...ROD_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, mst: 45 },
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020200',
  },
  {
    id: 'rabbit_wand',
    label: "Rabbit Wand",
    requirement: "348 MST",
    maxGrind: 0,
    special: "Chaos",
    atpMin: 120,
    atpMax: 230,
    ata: 48,
    ...ROD_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, mst: 45 },
    compatibleClasses: ['fomarl', 'fonewearl'],
    hex: '020200',
  },
  {
    id: 'battle_verge',
    label: "Battle Verge",
    requirement: "460 MST",
    maxGrind: 15,
    special: "Devil's",
    atpMin: 130,
    atpMax: 185,
    ata: 41,
    ...ROD_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, dfp: 25 },
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020200',
  },
  {
    id: 'brave_hammer',
    label: "Brave Hammer",
    requirement: "470 MST",
    maxGrind: 15,
    special: "Spirit",
    atpMin: 170,
    atpMax: 220,
    ata: 43,
    ...ROD_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, dfp: 30 },
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020200',
  },
  {
    id: 'alive_aqhu',
    label: "Alive Aqhu",
    requirement: "480 MST",
    maxGrind: 15,
    special: "Fill",
    atpMin: 210,
    atpMax: 230,
    ata: 45,
    ...ROD_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, dfp: 35 },
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020200',
  },
  {
    id: 'hildebears_cane',
    label: "Hildebear's Cane",
    requirement: "400 MST",
    maxGrind: 9,
    special: "Foie",
    atpMin: 220,
    atpMax: 230,
    ata: 50,
    ...ROD_WEAPON_DEFAULTS,
    hex: '020200',
  },
  {
    id: 'valkyrie',
    label: "Valkyrie",
    requirement: "500 ATP",
    maxGrind: 33,
    special: "None",
    atpMin: 600,
    atpMax: 600,
    ata: 66,
    ...ROD_WEAPON_DEFAULTS,
    hex: '020200',
  },
  {
    id: 'fatsia',
    label: "Fatsia",
    requirement: "590 MST",
    maxGrind: 0,
    special: "None",
    atpMin: 219,
    atpMax: 280,
    ata: 45,
    ...ROD_WEAPON_DEFAULTS,
    hex: '020200',
  },
  {
    id: 'plantain_leaf',
    label: "Plantain Leaf",
    requirement: "590 MST",
    maxGrind: 0,
    special: "None",
    atpMin: 219,
    atpMax: 280,
    ata: 45,
    ...ROD_WEAPON_DEFAULTS,
    hex: '020200',
  },
  {
    id: 'branch_of_pakupaku',
    label: "Branch of Pakupaku",
    requirement: "600 MST",
    maxGrind: 0,
    special: "None",
    atpMin: 240,
    atpMax: 267,
    ata: 45,
    ...ROD_WEAPON_DEFAULTS,
    hex: '020200',
  },
  {
    id: 'hildeblues_cane',
    label: "Hildeblue's Cane",
    requirement: "700 MST",
    maxGrind: 9,
    special: "Gibarta",
    atpMin: 290,
    atpMax: 300,
    ata: 52,
    ...ROD_WEAPON_DEFAULTS,
    hex: '020200',
  },
  {
    id: 'caduceus',
    label: "Caduceus",
    requirement: "720 MST",
    maxGrind: 0,
    special: "Foie",
    atpMin: 360,
    atpMax: 360,
    ata: 54,
    ...ROD_WEAPON_DEFAULTS,
    hex: '020200',
  },
  {
    id: 'demonic_fork',
    label: "Demonic Fork",
    requirement: "720 MST",
    maxGrind: 0,
    special: "King's",
    atpMin: 325,
    atpMax: 340,
    ata: 50,
    ...ROD_WEAPON_DEFAULTS,
    hex: '020200',
  },
  {
    id: 'sorcerers_cane',
    label: "Sorcerer's Cane",
    requirement: "756 MST",
    maxGrind: 0,
    special: "Geist",
    atpMin: 360,
    atpMax: 360,
    ata: 53,
    ...ROD_WEAPON_DEFAULTS,
    hex: '020200',
  },
  {
    id: 'glide_divine',
    label: "Glide Divine",
    requirement: "900 MST",
    maxGrind: 0,
    special: "Anti",
    atpMin: 185,
    atpMax: 400,
    ata: 34,
    ...ROD_WEAPON_DEFAULTS,
    hex: '020200',
  },
  {
    id: 'siren_glass_hammer',
    label: "Siren Glass Hammer",
    requirement: "900 MST",
    maxGrind: 0,
    special: "Grants",
    atpMin: 390,
    atpMax: 450,
    ata: 55,
    ...ROD_WEAPON_DEFAULTS,
    hex: '020200',
  },
  {
    id: 'striker_of_chao',
    label: "Striker of Chao",
    requirement: "695 MST",
    maxGrind: 0,
    special: "Arrest",
    atpMin: 300,
    atpMax: 325,
    ata: 50,
    ...ROD_WEAPON_DEFAULTS,
    hex: '020200',
  },
  {
    id: 'mercurius_rod',
    label: "Mercurius Rod",
    requirement: "770 MST",
    maxGrind: 0,
    special: "Gifoie",
    atpMin: 390,
    atpMax: 400,
    ata: 58,
    ...ROD_WEAPON_DEFAULTS,
    hex: '020200',
  },
  {
    id: 'dark_bridge',
    label: "Dark Bridge",
    requirement: "900 MST",
    maxGrind: 0,
    special: "None",
    atpMin: 185,
    atpMax: 400,
    ata: 34,
    ...ROD_WEAPON_DEFAULTS,
    hex: '020200',
  },
  {
    id: 'psycho_wand',
    label: "Psycho Wand",
    requirement: "900 MST",
    maxGrind: 0,
    special: "See Notes",
    atpMin: 395,
    atpMax: 400,
    ata: 55,
    ...ROD_WEAPON_DEFAULTS,
    hex: '020200',
  },
  {
    id: 'typero_rod',
    label: "TypeRO/Rod",
    requirement: "350 MST",
    maxGrind: 90,
    special: "None",
    atpMin: 10,
    atpMax: 10,
    ata: 40,
    ...ROD_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, dfp: 50 },
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020200',
  },
  {
    id: 'typero_halbert',
    label: "TypeRO/Halbert",
    requirement: "350 ATP",
    maxGrind: 100,
    special: "None",
    atpMin: 10,
    atpMax: 80,
    ata: 40,
    ...ROD_WEAPON_DEFAULTS,
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal', 'ramar', 'ramarl', 'racast', 'racaseal'],
    hex: '020200',
  },
  {
    id: 'typero_sword',
    label: "TypeRO/Sword",
    requirement: "350 ATP",
    maxGrind: 100,
    special: "None",
    atpMin: 10,
    atpMax: 100,
    ata: 35,
    ...ROD_WEAPON_DEFAULTS,
    compatibleClasses: ['humar', 'hunewearl', 'hucast', 'hucaseal'],
    hex: '020200',
  },
  {
    id: 'es_rod',
    label: "ES Rod",
    requirement: "800 MST",
    maxGrind: 180,
    special: "Varies",
    atpMin: 10,
    atpMax: 10,
    ata: 50,
    ...ROD_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, dfp: 35 },
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020200',
  },
// --- WANDS ---
  {
    id: 'wand',
    label: "Wand",
    requirement: "114 MST",
    maxGrind: 15,
    special: "None",
    atpMin: 3,
    atpMax: 10,
    ata: 25,
    ...WAND_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, mst: 5 },
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020300',
  },
  {
    id: 'staff',
    label: "Staff",
    requirement: "250 MST",
    maxGrind: 15,
    special: "None",
    atpMin: 10,
    atpMax: 30,
    ata: 27,
    ...WAND_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, mst: 10 },
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020300',
  },
  {
    id: 'baton',
    label: "Baton",
    requirement: "380 MST",
    maxGrind: 10,
    special: "None",
    atpMin: 35,
    atpMax: 50,
    ata: 28,
    ...WAND_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, mst: 15 },
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020300',
  },
  {
    id: 'scepter',
    label: "Scepter",
    requirement: "460 MST",
    maxGrind: 10,
    special: "None",
    atpMin: 55,
    atpMax: 75,
    ata: 30,
    ...WAND_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, mst: 20 },
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020300',
  },
  {
    id: 'game_magazine',
    label: "Game Magazine",
    requirement: "Aucun",
    maxGrind: 0,
    special: "None",
    atpMin: 1,
    atpMax: 1,
    ata: 1,
    ...WAND_WEAPON_DEFAULTS,
    hex: '020300',
  },
  {
    id: 'login',
    label: "LOGiN",
    requirement: "25 ATP",
    maxGrind: 0,
    special: "None",
    atpMin: 5,
    atpMax: 5,
    ata: 25,
    ...WAND_WEAPON_DEFAULTS,
    hex: '020300',
  },
  {
    id: 'marinas_bag',
    label: "Marina's Bag",
    requirement: "348 MST",
    maxGrind: 0,
    special: "Havoc",
    atpMin: 10,
    atpMax: 180,
    ata: 10,
    ...WAND_WEAPON_DEFAULTS,
    hex: '020300',
  },
  {
    id: 'fire_scepter_agni',
    label: "Fire Scepter: Agni",
    requirement: "470 MST",
    maxGrind: 9,
    special: "Flame",
    atpMin: 70,
    atpMax: 95,
    ata: 31,
    ...WAND_WEAPON_DEFAULTS,
    hex: '020300',
  },
  {
    id: 'ice_staff_dagon',
    label: "Ice Staff: Dagon",
    requirement: "480 MST",
    maxGrind: 9,
    special: "Freeze",
    atpMin: 73,
    atpMax: 105,
    ata: 33,
    ...WAND_WEAPON_DEFAULTS,
    hex: '020300',
  },
  {
    id: 'storm_wand_indra',
    label: "Storm Wand: Indra",
    requirement: "490 MST",
    maxGrind: 9,
    special: "Storm",
    atpMin: 105,
    atpMax: 120,
    ata: 34,
    ...WAND_WEAPON_DEFAULTS,
    hex: '020300',
  },
  {
    id: 'technical_crozier',
    label: "Technical Crozier",
    requirement: "285 MST",
    maxGrind: 0,
    special: "Barta",
    atpMin: 130,
    atpMax: 135,
    ata: 36,
    ...WAND_WEAPON_DEFAULTS,
    hex: '020300',
  },
  {
    id: 'the_sigh_of_a_god',
    label: "The Sigh of a God",
    requirement: "653 MST",
    maxGrind: 0,
    special: "Gizonde",
    atpMin: 175,
    atpMax: 180,
    ata: 40,
    ...WAND_WEAPON_DEFAULTS,
    hex: '020300',
  },
  {
    id: 'earth_wand_brownie',
    label: "Earth Wand: Brownie",
    requirement: "770 MST",
    maxGrind: 20,
    special: "Gush",
    atpMin: 370,
    atpMax: 670,
    ata: 59,
    ...WAND_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, mst: 50 },
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020300',
  },
  {
    id: 'solferino',
    label: "Solferino",
    requirement: "850 MST",
    maxGrind: 0,
    special: "Resta",
    atpMin: 250,
    atpMax: 300,
    ata: 45,
    ...WAND_WEAPON_DEFAULTS,
    hex: '020300',
  },
  {
    id: 'plantain_fan',
    label: "Plantain Fan",
    requirement: "630 MST",
    maxGrind: 40,
    special: "See Notes",
    atpMin: 95,
    atpMax: 150,
    ata: 42,
    ...WAND_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, mst: 55 },
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020300',
  },
  {
    id: 'twinkle_star',
    label: "Twinkle Star",
    requirement: "670 MST",
    maxGrind: 0,
    special: "Tempest",
    atpMin: 175,
    atpMax: 175,
    ata: 40,
    ...WAND_WEAPON_DEFAULTS,
    hex: '020300',
  },
  {
    id: 'magical_piece',
    label: "Magical Piece",
    requirement: "800 MST",
    maxGrind: 0,
    special: "Zonde",
    atpMin: 240,
    atpMax: 240,
    ata: 42,
    ...WAND_WEAPON_DEFAULTS,
    hex: '020300',
  },
  {
    id: 'prophets_of_motav',
    label: "Prophets of Motav",
    requirement: "900 MST",
    maxGrind: 0,
    special: "Jellen",
    atpMin: 90,
    atpMax: 250,
    ata: 45,
    ...WAND_WEAPON_DEFAULTS,
    hex: '020300',
  },
  {
    id: 'typewa_wand',
    label: "TypeWA/Wand",
    requirement: "350 MST",
    maxGrind: 60,
    special: "None",
    atpMin: 10,
    atpMax: 10,
    ata: 45,
    ...WAND_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, mst: 50 },
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020300',
  },
  {
    id: 'es_wand',
    label: "ES Wand",
    requirement: "800 MST",
    maxGrind: 100,
    special: "Varies",
    atpMin: 10,
    atpMax: 10,
    ata: 40,
    ...WAND_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, mst: 35 },
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020300',
  },
// --- CARDS ---
  {
    id: 'kanei_tsuho',
    label: "Kan'ei Tsuho",
    requirement: "Aucun",
    maxGrind: 0,
    special: "Charge",
    atpMin: 1,
    atpMax: 1,
    ata: 1,
    ...CARD_WEAPON_DEFAULTS,
    hex: '020400',
  },
  {
    id: 'amore_rose',
    label: "Amore Rose",
    requirement: "150 MST",
    maxGrind: 0,
    special: "None",
    atpMin: 5,
    atpMax: 7,
    ata: 10,
    ...CARD_WEAPON_DEFAULTS,
    compatibleClasses: ['humar', 'hunewearl', 'ramar', 'ramarl', 'fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020400',
  },
  {
    id: 'kunai',
    label: "Kunai",
    requirement: "412 ATP",
    maxGrind: 0,
    special: "Arrest",
    atpMin: 95,
    atpMax: 175,
    ata: 32,
    ...CARD_WEAPON_DEFAULTS,
    hex: '020400',
  },
  {
    id: 'syringe',
    label: "Syringe",
    requirement: "412 ATP",
    maxGrind: 0,
    special: "King's",
    atpMin: 95,
    atpMax: 175,
    ata: 32,
    ...CARD_WEAPON_DEFAULTS,
    hex: '020400',
  },
  {
    id: 'talis',
    label: "Talis",
    requirement: "475 MST",
    maxGrind: 9,
    special: "Mind",
    atpMin: 120,
    atpMax: 180,
    ata: 38,
    ...CARD_WEAPON_DEFAULTS,
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020400',
  },
  {
    id: 'mahu',
    label: "Mahu",
    requirement: "480 MST",
    maxGrind: 9,
    special: "Soul",
    atpMin: 120,
    atpMax: 200,
    ata: 40,
    ...CARD_WEAPON_DEFAULTS,
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020400',
  },
  {
    id: 'guardianna',
    label: "Guardianna",
    requirement: "490 MST",
    maxGrind: 9,
    special: "Spirit",
    atpMin: 200,
    atpMax: 280,
    ata: 40,
    ...CARD_WEAPON_DEFAULTS,
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020400',
  },
  {
    id: 'hitogata',
    label: "Hitogata",
    requirement: "495 MST",
    maxGrind: 9,
    special: "Soul",
    atpMin: 150,
    atpMax: 230,
    ata: 50,
    ...CARD_WEAPON_DEFAULTS,
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020400',
  },
  {
    id: 'gal_wind',
    label: "Gal Wind",
    requirement: "800 MST",
    maxGrind: 15,
    special: "See Notes",
    atpMin: 270,
    atpMax: 310,
    ata: 40,
    ...CARD_WEAPON_DEFAULTS,
    bonuses: { ...ZERO_WEAPON_STAT_BONUSES, evp: -15 },
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020400',
  },
  {
    id: 'viridia_card',
    label: "Viridia Card",
    requirement: "200 MST",
    maxGrind: 0,
    special: "None",
    atpMin: 200,
    atpMax: 250,
    ata: 40,
    ...CARD_WEAPON_DEFAULTS,
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020400',
  },
  {
    id: 'greenill_card',
    label: "Greenill Card",
    requirement: "200 MST",
    maxGrind: 0,
    special: "None",
    atpMin: 200,
    atpMax: 250,
    ata: 40,
    ...CARD_WEAPON_DEFAULTS,
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020400',
  },
  {
    id: 'skyly_card',
    label: "Skyly Card",
    requirement: "200 MST",
    maxGrind: 0,
    special: "None",
    atpMin: 200,
    atpMax: 250,
    ata: 40,
    ...CARD_WEAPON_DEFAULTS,
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020400',
  },
  {
    id: 'bluefull_card',
    label: "Bluefull Card",
    requirement: "200 MST",
    maxGrind: 0,
    special: "None",
    atpMin: 200,
    atpMax: 250,
    ata: 40,
    ...CARD_WEAPON_DEFAULTS,
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020400',
  },
  {
    id: 'purplenum_card',
    label: "Purplenum Card",
    requirement: "200 MST",
    maxGrind: 0,
    special: "None",
    atpMin: 200,
    atpMax: 250,
    ata: 40,
    ...CARD_WEAPON_DEFAULTS,
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020400',
  },
  {
    id: 'pinkal_card',
    label: "Pinkal Card",
    requirement: "200 MST",
    maxGrind: 0,
    special: "None",
    atpMin: 200,
    atpMax: 250,
    ata: 40,
    ...CARD_WEAPON_DEFAULTS,
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020400',
  },
  {
    id: 'redria_card',
    label: "Redria Card",
    requirement: "200 MST",
    maxGrind: 0,
    special: "None",
    atpMin: 200,
    atpMax: 250,
    ata: 40,
    ...CARD_WEAPON_DEFAULTS,
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020400',
  },
  {
    id: 'oran_card',
    label: "Oran Card",
    requirement: "200 MST",
    maxGrind: 0,
    special: "None",
    atpMin: 200,
    atpMax: 250,
    ata: 40,
    ...CARD_WEAPON_DEFAULTS,
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020400',
  },
  {
    id: 'yellowboze_card',
    label: "Yellowboze Card",
    requirement: "200 MST",
    maxGrind: 0,
    special: "None",
    atpMin: 200,
    atpMax: 250,
    ata: 30,
    ...CARD_WEAPON_DEFAULTS,
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020400',
  },
  {
    id: 'whitill_card',
    label: "Whitill Card",
    requirement: "200 MST",
    maxGrind: 0,
    special: "None",
    atpMin: 200,
    atpMax: 250,
    ata: 46,
    ...CARD_WEAPON_DEFAULTS,
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020400',
  },
  {
    id: 'dancing_hitogata',
    label: "Dancing Hitogata",
    requirement: "900 MST",
    maxGrind: 0,
    special: "Geist",
    atpMin: 350,
    atpMax: 354,
    ata: 50,
    ...CARD_WEAPON_DEFAULTS,
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020400',
  },
  {
    id: 'es_cards',
    label: "ES Cards",
    requirement: "800 MST",
    maxGrind: 150,
    special: "Varies",
    atpMin: 10,
    atpMax: 10,
    ata: 45,
    ...CARD_WEAPON_DEFAULTS,
    compatibleClasses: ['fomar', 'fomarl', 'fonewm', 'fonewearl'],
    hex: '020400',
  },

]
